/* MILITREE OPS · admin console */
const ADMIN={};
const who=k=>PEOPLE[k];
const ANAV=[['Pipeline',[['overview','layout','Overview'],['enquiries','inbox','Enquiries','en'],['quotes','file-text','Quotes'],['jobs','calendar','Jobs & crew calendar']]],['People',[['crew','hardhat','Crew register','cr'],['clients','briefcase','Clients']]],['Money',[['invoices','receipt','Invoices & payments',1]]],['Setup',[['settings','cog','Settings']]]];
const pips=()=>({en:S.enq.filter(e=>e.new).length,cr:S.crewApps.length});
const COLS=[['New enquiry','coral'],['Survey booked','gold'],['Quote sent','sea'],['Scheduled','deep']];
const stPill=s=>({Paid:'pill-ok',Overdue:'pill-bad',Available:'pill-ok','On job':'pill-navy',Unavailable:'pill-soft'}[s]||(s.startsWith('Due')?'pill-warn':s.startsWith('From')?'pill-warn':'pill-soft'));
ADMIN.shell=()=>{ const pp=pips(); const page=S.adminPage; const titles={overview:['Morning, Jamie','Mon 15 September · 2 new enquiries · Kingston Lacy starts 5 Oct'],enquiries:['Enquiries','Every job from first message to crew on site'],quotes:['Quotes','Itemised, sent online, accepted with a deposit'],jobs:['Jobs & crew calendar','Who is where, this week and next'],crew:['Crew register','Ticketed climbers and operators, paid direct'],clients:['Clients','Estates, trusts, councils and homeowners'],invoices:['Invoices & payments','Deposits, balances and what is overdue'],settings:['Settings','Brand, rates, documents and the two-business back office']};
  return `<div class="shell"><aside class="side"><div class="brand"><img src="${LOGO}" alt=""><div><div class="wm">Militree Ops</div><div class="sub">Forestry back office</div></div></div>${ANAV.map(([g,items])=>`<div class="navlabel">${g}</div>${items.map(([k,i,l,p])=>`<button class="nav ${page===k?'on':''}" data-act="adm-page" data-p="${k}">${ico(i,17)} ${l}${p?(typeof p==='number'?`<span class="pipn">${p}</span>`:pp[p]?`<span class="pipn">${pp[p]}</span>`:''):''}</button>`).join('')}`).join('')}
    <div class="navlabel">Switch business</div><a class="nav" href="../royal/index.html#admin" style="display:flex;align-items:center;gap:11px;padding:10px 11px;border-radius:10px;font-size:.83rem;font-weight:600;color:rgba(255,255,255,.72)"><img src="../assets/logo/royal.png" style="width:20px;height:20px;border-radius:50%" alt=""> Royal Home &amp; Garden</a>
    <div class="foot"><div class="me"><img src="${who('jamie').img}" alt=""><div><div class="n">Jamie Doxey</div><div class="s">Owner</div></div></div><button class="nav" style="margin-top:8px" data-act="go" data-to="home">${ico('external',16)} View public site</button></div></aside>
    <main class="main"><div class="topbar"><div><h1>${titles[page][0]}</h1><div class="sub">${titles[page][1]}</div></div><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="2 enquiries, 1 overdue invoice, 2 crew applications">${ico('bell',15)} Notifications</button><button class="btn btn-sm btn-coral" data-act="adm-page" data-p="quotes">${ico('plus',14)} New quote</button></div><div class="content">${(ADMIN.pages[page]||ADMIN.pages.overview)()}</div></main></div>`; };
ADMIN.pages={};
const enqCard=e=>`<div class="jobcard" data-act="enq-open" data-id="${e.id}"><div class="t"><b>${e.title}</b>${e.new?'<span class="pill pill-coral">New</span>':''}</div><div class="m"><span>${ico('user',11)} ${who(e.who).n}</span><span>${ico('map-pin',11)} ${e.loc}</span></div><div class="m"><span>${ico('ruler',11)} ${e.size}</span><span>${ico('clock',11)} ${e.when}</span></div>${e.survey?`<div class="v" style="color:var(--gold)">${ico('calendar',14)} ${e.survey}</div>`:''}${e.quote&&e.col>=2?`<div class="v">${gbp(e.quote)}${e.sent?` <span class="muted" style="font-weight:600;font-size:.72rem">sent ${e.sent}</span>`:''}</div>`:''}${e.dates?`<div class="v" style="color:var(--deep)">${ico('calendar',14)} ${e.dates}</div>`:''}${e.crew?`<div class="crew">${e.crew.map(c=>`<img src="${who(c).img}" title="${who(c).n}" alt="">`).join('')}</div>`:''}</div>`;
ADMIN.pages.overview=()=>{ const pp=pips(); const won=[9,12,8,14,11,16,13,18];
  return `<div class="masthead"><img class="bg" src="${P('forest7')}" alt=""><div class="sc"></div><div class="in"><div><span class="kicker light">Next big job · 5 – 16 Oct</span><h2>Kingston Lacy <em>12 ha thinning</em></h2><p>Crew of 4 confirmed · RAMS issued · forwarder booked · 380 t estimated to ride-side.</p></div><span class="grow"></span><div class="spark"><div class="sp"><div class="k">Pipeline value</div><div class="v">£42.7k</div><div class="d">7 live enquiries</div></div><div class="sp"><div class="k">Invoiced · Sep</div><div class="v">£10.8k</div><div class="d">£2.4k overdue</div></div><div class="sp"><div class="k">Recruiter fees avoided</div><div class="v">£11.2k</div><div class="d">this year</div></div></div></div></div>
  <div class="grid g4"><div class="stat"><div class="k">New enquiries</div><div class="v">${pp.en}</div><div class="d coral">${ico('inbox',12)} reply today</div></div><div class="stat"><div class="k">Surveys this week</div><div class="v">2</div><div class="d sea">${ico('calendar',12)} Thu &amp; Sat</div></div><div class="stat"><div class="k">Quotes awaiting</div><div class="v">£20.6k</div><div class="d sea">${ico('file-text',12)} 2 sent, 1 viewed twice</div></div><div class="stat"><div class="k">Crew available Mon</div><div class="v">${S.crew.filter(c=>c.status==='Available').length}</div><div class="d up">${ico('hardhat',12)} ${S.crewApps.length} applications</div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Jobs won per month</h3><span class="grow"></span><span class="pill pill-soft">Last 8 months</span></div><div class="bd"><div class="mini">${won.map((w,i)=>`<span class="${i===7?'hi':''}" style="height:${Math.round(w/18*80)}px"></span>`).join('')}</div><div class="minilab">${['Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map(x=>`<span>${x}</span>`).join('')}</div></div></div>
    <div class="card"><div class="hd"><h3>Where work came from · 2026</h3></div><div class="bd"><div class="barrow">${[['Direct · website & referrals',31200,''],['Repeat estate contracts',26400,''],['Recruiters (declining)',9800,'coral'],['Instagram',4100,'']].map(([n,v,c])=>`<div class="b"><span class="nm">${n}</span><span class="tr"><i class="${c}" style="width:${v/31200*100}%"></i></span><span class="vv">${gbp(v)}</span></div>`).join('')}</div></div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Needs you</h3></div><div class="bd" style="padding-top:8px">${S.enq.filter(e=>e.col===0).map(e=>`<div class="row-item"><img src="${who(e.who).img}" style="width:44px;height:44px;border-radius:10px;object-fit:cover" alt=""><div><b>${e.title}</b><span>${who(e.who).n} · ${e.loc} · ${e.when}</span></div><div class="r"><button class="btn btn-sm btn-primary" data-act="enq-open" data-id="${e.id}">Open</button></div></div>`).join('')}${S.crewApps.map(a=>`<div class="row-item"><img src="${who(a.who).img}" style="width:44px;height:44px;border-radius:10px;object-fit:cover" alt=""><div><b>Crew application · ${who(a.who).n}</b><span>${a.tix.join(', ')} · ${a.when}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="adm-page" data-p="crew">Review</button></div></div>`).join('')}</div></div>
    <div class="card"><div class="hd"><h3>This week</h3><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="adm-page" data-p="jobs">Calendar</button></div><div class="bd" style="padding-top:8px">${[['22','Sep','Corfe beech dismantle','Jamie, Callum, Priya · 1 day · £2,350'],['18','Sep','Survey · Blandford ash','Rob Hale · 09:00 · storm damage'],['18','Sep','Survey · Broadstone copse','Sarah Pemberton · PM · 2 ha'],['25','Sep','Chipper service','Priya · Wareham yard']].map(([d,m,t,s])=>`<div class="event-row"><div class="d"><b>${d}</b><span>${m}</span></div><div class="t"><b>${t}</b><span>${s}</span></div></div>`).join('')}</div></div></div>`; };
ADMIN.pages.enquiries=()=>`<div class="pagehead"><div><h2>Pipeline</h2><p>Drag or click through: enquiry → survey → quote → scheduled. Every move sends the client a message and sets a reminder for you.</p></div><span class="grow"></span><span class="pill pill-sea">${gbp(S.enq.reduce((a,e)=>a+(e.quote||0),0))} quoted or scheduled</span></div>
  <div class="board">${COLS.map(([t,c],i)=>`<div class="col"><div class="ch"><i class="${c}"></i>${t}<span class="cnt">${S.enq.filter(e=>e.col===i).length}</span></div>${S.enq.filter(e=>e.col===i).map(enqCard).join('')}</div>`).join('')}</div>
  <div class="grid g3 mt2"><div class="card pad"><b>Auto-replies</b><p class="muted" style="font-size:.82rem;margin-top:6px;line-height:1.5">New enquiry: instant WhatsApp + email with your survey slots. Quote sent: reminder at 48 h and 7 days.</p><div class="mt" style="display:flex;gap:10px;align-items:center;font-size:.8rem;font-weight:700">On <span class="tog on" data-act="toggle"></span></div></div><div class="card pad"><b>Conversion · 2026</b><div class="mt"><div class="barrow">${[['Enquiry → survey',82],['Survey → quote',94],['Quote → won',61]].map(([n,v])=>`<div class="b"><span class="nm">${n}</span><span class="tr"><i style="width:${v}%"></i></span><span class="vv">${v}%</span></div>`).join('')}</div></div></div><div class="card pad"><b>Recruiter enquiries</b><p class="muted" style="font-size:.82rem;margin-top:6px;line-height:1.5">3 this month. Marked separately so you can see what they are worth versus direct work.</p><div class="mt"><span class="pill pill-coral">£9.8k via recruiters</span> <span class="pill pill-ok">£31.2k direct</span></div></div></div>`;
ADMIN.pages.quotes=()=>{ const q=QUOTE; const st=S.quote.state;
  return `<div class="grid g4"><div class="stat"><div class="k">Sent, awaiting</div><div class="v">2</div><div class="d sea">${ico('file-text',12)} £20,600</div></div><div class="stat"><div class="k">Accepted · 30d</div><div class="v">3</div><div class="d up">${ico('check-circle',12)} £24,500</div></div><div class="stat"><div class="k">Avg turnaround</div><div class="v">31 h</div><div class="d up">${ico('clock',12)} survey → quote</div></div><div class="stat"><div class="k">Win rate</div><div class="v">61%</div><div class="d sea">${ico('trending-up',12)} +9 pts</div></div></div>
  <div class="card mt"><div class="hd"><h3>Quote builder · ${q.id}</h3><span class="s">${q.title} · ${who(q.client).n}</span><span class="grow"></span><span class="pill ${st==='accepted'?'pill-ok':'pill-warn'}">${st==='accepted'?'Accepted · deposit paid':'Sent 12 Sep · viewed twice'}</span></div><div class="bd">
    <div class="quotehead"><span>Line item</span><span>Qty</span><span class="num">Rate</span><span class="num">Total</span></div>${q.lines.map(([t,qy,r,tt])=>`<div class="quoteline"><div><input class="input" value="${t}" style="padding:8px 10px"></div><input class="input" value="${qy}" style="padding:8px 10px"><input class="input num" value="${r}" style="padding:8px 10px;text-align:right"><span class="num" style="${tt<0?'color:var(--success)':''}">${tt<0?'−':''}${gbp(Math.abs(tt))}</span></div>`).join('')}
    <div style="display:flex;gap:8px;margin-top:12px"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Line added">${ico('plus',13)} Add line</button><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Rate card: thinning £1,400/ha · felling £480/day · planting £2.40/tree">${ico('list',13)} From rate card</button><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Timber credit recalculated at £2.50/t">${ico('trees',13)} Timber credit</button><span class="grow"></span><div style="text-align:right;font-size:.84rem"><div class="muted">Subtotal ${gbp(q.sub)} · VAT ${gbp(q.vat)}</div><div style="font-size:1.2rem;font-weight:800">Total ${gbp(q.tot)}</div><div class="muted">Deposit 25% · ${gbp(q.deposit)}</div></div></div>
    <div class="divider"></div><div class="grid g3"><div class="field"><label>Start</label><input class="input" value="${q.start}"></div><div class="field"><label>Duration</label><input class="input" value="${q.dur}"></div><div class="field"><label>Crew</label><input class="input" value="${q.crew}"></div></div>
    <div class="mt" style="display:flex;gap:8px;flex-wrap:wrap">${['RAMS-0412','Insurance certs','NPTC · crew of 4','Marked-tree map'].map(a=>`<span class="pill pill-navy">${ico('file-text',10)} ${a}</span>`).join('')}<button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Attach documents">${ico('plus',12)} Attach</button></div>
    <div class="mt2" style="display:flex;gap:10px;justify-content:flex-end"><button class="btn btn-ghost" data-act="go" data-to="quote">${ico('eye',14)} Client view</button><button class="btn btn-ghost" data-act="soon" data-msg="PDF generated">${ico('download',14)} PDF</button><button class="btn btn-coral" data-act="soon" data-msg="Quote re-sent by email & WhatsApp · reminder in 48 h">${ico('send',14)} Send to client</button></div></div></div>
  <div class="card mt"><div class="hd"><h3>All quotes</h3></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Quote</th><th>Client</th><th>Job</th><th>Total</th><th>Status</th><th>Sent</th><th></th></tr></thead><tbody>${[['Q-0412','hinton','Hinton Wood · 8 ha thinning',17280,st==='accepted'?'Accepted':'Viewed ×2','12 Sep'],['Q-0411','poole','40 street trees · crown lift',7440,'Sent','11 Sep'],['Q-0409','nt','Kingston Lacy · 12 ha thinning',23760,'Accepted','28 Aug'],['Q-0408','rob','Beech dismantle · Corfe',2820,'Accepted','26 Aug'],['Q-0405','dwt','Ride widening · phase 3',4980,'Declined','14 Aug']].map(([id,c,j,t,s,d])=>`<tr><td><b>${id}</b></td><td><div class="thumbcell"><img class="sq" src="${who(c).img}" alt=""><b>${who(c).n}</b></div></td><td>${j}</td><td class="num">${gbp(t)}</td><td><span class="pill ${s==='Accepted'?'pill-ok':s==='Declined'?'pill-soft':'pill-warn'}">${s}</span></td><td>${d}</td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>`; };
ADMIN.pages.jobs=()=>`<div class="grid g4"><div class="stat"><div class="k">Jobs this week</div><div class="v">3</div><div class="d sea">${ico('calendar',12)} 1 job, 2 surveys</div></div><div class="stat"><div class="k">Crew days booked</div><div class="v">14</div><div class="d up">${ico('hardhat',12)} of 20 available</div></div><div class="stat"><div class="k">Kit</div><div class="v">OK</div><div class="d sea">${ico('truck',12)} chipper service Fri</div></div><div class="stat"><div class="k">Weather · Corfe Mon</div><div class="v">Dry</div><div class="d sea">${ico('wind',12)} SW 12 kt</div></div></div>
  <div class="card mt"><div class="hd"><h3>Week of 21 September · crew</h3><span class="grow"></span><div class="chips"><button class="chip" data-act="soon">← Prev</button><button class="chip on">This week</button><button class="chip" data-act="soon">Next →</button></div><button class="btn btn-sm btn-coral" data-act="soon" data-msg="Assign crew: pick a job, tick names, they get a text">${ico('user-plus',13)} Assign crew</button></div><div class="bd"><div class="calweek"><div class="h"></div>${JOBS_WEEK.days.map(d=>`<div class="h">${d}</div>`).join('')}${JOBS_WEEK.rows.map(([w,cells])=>`<div class="r"><img src="${who(w).img}" alt="">${who(w).n.split(' ')[0]}</div>${cells.map(c=>{const [t,k]=c.split('|');return `<div class="c"><span class="j ${k||''}">${t}</span></div>`;}).join('')}`).join('')}</div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Scheduled jobs</h3></div><div class="bd" style="padding-top:8px">${S.enq.filter(e=>e.col===3).map(e=>`<div class="row-item"><img src="${who(e.who).img}" style="width:44px;height:44px;border-radius:10px;object-fit:cover" alt=""><div><b>${e.title}</b><span>${e.dates} · ${gbp(e.quote)} · ${e.crew.length} crew</span></div><div class="r"><div class="crew" style="display:flex">${e.crew.map(c=>`<img src="${who(c).img}" style="width:26px;height:26px;border-radius:50%;object-fit:cover;border:2px solid #fff;margin-left:-6px" alt="">`).join('')}</div></div></div>`).join('')}</div></div>
    <div class="card"><div class="hd"><h3>Job pack · Corfe beech · Mon 22</h3></div><div class="bd">${[['file-text','RAMS-0408 issued to crew','Sent Sun 20:00 automatically'],['map-pin','What3words · ///shrub.thatch.lane','Parking at the pub car park'],['clipboard','Kit list','Rigging kit, 200 ft lowering line, chipper, 2 saws'],['phone','Client · Rob Hale','07700 900 789 · on site from 07:30'],['camera','Photo prompts','Before, rigging points, after, timber stack']].map(([i,t,s])=>`<div class="row-item"><div style="color:var(--sea)">${ico(i,18)}</div><div><b>${t}</b><span>${s}</span></div></div>`).join('')}</div></div></div>`;
ADMIN.pages.crew=()=>`<div class="grid g4"><div class="stat"><div class="k">On register</div><div class="v">${S.crew.length+16}</div><div class="d up">${ico('hardhat',12)} 14 climbers, 8 ground</div></div><div class="stat"><div class="k">Available next week</div><div class="v">${S.crew.filter(c=>c.status==='Available').length+9}</div><div class="d sea">${ico('calendar',12)} across Dorset</div></div><div class="stat"><div class="k">Certs expiring · 60d</div><div class="v">3</div><div class="d coral">${ico('alert',12)} first aid × 2, CS39 × 1</div></div><div class="stat"><div class="k">Paid out · Sep</div><div class="v">£6,840</div><div class="d sea">${ico('pound',12)} 0% agency fee</div></div></div>
  ${S.crewApps.length?`<div class="pagehead mt2"><div><h2>Applications</h2><p>Certificates checked against NPTC. Approve and they appear on the register and can be assigned.</p></div></div><div class="app">${S.crewApps.map(a=>`<div class="appcard"><div class="who"><img src="${who(a.who).img}" alt=""><div><b>${who(a.who).n}</b><span>${who(a.who).role} · ${a.when}</span></div><span class="pill pill-coral">To review</span></div><blockquote>${a.note}</blockquote><div class="facts">${a.tix.map(t=>`<span>${ico('award',13)} ${t}</span>`).join('')}<span>${ico('shield-check',13)} Certs verified</span></div><div class="acts"><button class="btn btn-sm btn-sea" data-act="crew-approve" data-who="${a.who}">${ico('check',13)} Add to register</button><button class="btn btn-sm btn-ghost" data-act="crew-decline" data-who="${a.who}">Not now</button><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Certificates open">${ico('file-text',13)} Certs</button></div></div>`).join('')}</div>`:''}
  <div class="card mt2"><div class="hd"><h3>Register</h3><span class="grow"></span><div class="toolbar" style="margin:0"><div class="search">${ico('search',15)}<input placeholder="Search name or ticket"></div></div><div class="chips"><button class="chip on">All</button><button class="chip" data-act="soon">Climbers</button><button class="chip" data-act="soon">Ground</button><button class="chip" data-act="soon">Plant</button></div></div>
    <div class="tblwrap"><table class="tbl"><thead><tr><th>Crew</th><th>Tickets</th><th>Day rate</th><th>Status</th><th>Days · 2026</th><th></th></tr></thead><tbody>${S.crew.map((c,i)=>`<tr><td><div class="thumbcell"><img src="${who(c.who).img}" alt=""><div><b>${who(c.who).n}</b><div class="s">${who(c.who).role}</div></div></div></td><td><div style="display:flex;gap:4px;flex-wrap:wrap">${c.tix.map(t=>`<span class="pill pill-navy">${t}</span>`).join('')}</div></td><td class="num">${gbp(c.day)}</td><td><span class="pill ${stPill(c.status)}">${c.status}${c.job?' · '+c.job:''}</span></td><td class="num">${[112,64,58,71,22,9,0,0][i]||0}</td><td><div class="acts">${c.status==='Available'?`<button class="btn btn-sm btn-sea" data-act="crew-assign" data-who="${c.who}">${ico('calendar',13)} Assign</button>`:''}<button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Profile opens: certs, availability, pay history">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>`;
ADMIN.pages.clients=()=>`<div class="card"><div class="hd"><h3>Clients</h3><span class="grow"></span><button class="btn btn-sm btn-coral" data-act="soon" data-msg="New client form">${ico('plus',13)} Add client</button></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Client</th><th>Type</th><th>Jobs</th><th>Lifetime</th><th>Contract</th><th>Last job</th><th></th></tr></thead><tbody>${[['nt','Estate · National Trust',6,68400,'Annual programme','Sep 2026'],['hinton','Private estate',3,21600,'—','Jun 2026'],['dwt','Charity · reserves',4,14900,'Annual programme','Aug 2026'],['poole','Local authority',2,8600,'Framework','Aug 2026'],['rob','Homeowner',1,2350,'—','Sep 2026'],['sarah','Homeowner',0,0,'—','Enquiry']].map(([k,t,j,l,c,d])=>`<tr><td><div class="thumbcell"><img class="sq" src="${who(k).img}" alt=""><div><b>${who(k).n}</b><div class="s">${who(k).role}</div></div></div></td><td>${t}</td><td class="num">${j}</td><td class="num">${gbp(l)}</td><td>${c!=='—'?`<span class="pill pill-sea">${c}</span>`:'—'}</td><td>${d}</td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Estate contracts</h3></div><div class="bd">${[['National Trust · Purbeck','£2,400 / month · 12 ha thinning + storm cover · renews Apr 2027'],['Dorset Wildlife Trust','£1,800 / month · rides, halo work, monitoring · renews Jan 2027']].map(([t,s])=>`<div class="row-item"><div style="color:var(--sea)">${ico('clipboard',18)}</div><div><b>${t}</b><span>${s}</span></div><div class="r"><span class="pill pill-ok">Active</span></div></div>`).join('')}</div></div><div class="card"><div class="hd"><h3>Referral sources</h3></div><div class="bd"><div class="barrow">${[['Word of mouth',14],['Website',9],['Instagram',4],['Recruiter',3]].map(([n,v])=>`<div class="b"><span class="nm">${n}</span><span class="tr"><i style="width:${v/14*100}%"></i></span><span class="vv">${v}</span></div>`).join('')}</div></div></div></div>`;
ADMIN.pages.invoices=()=>`<div class="grid g4"><div class="stat"><div class="k">Outstanding</div><div class="v">£5,520</div><div class="d coral">${ico('alert',12)} £2,400 overdue</div></div><div class="stat"><div class="k">Deposits held</div><div class="v">£4,190</div><div class="d sea">${ico('lock',12)} 2 jobs</div></div><div class="stat"><div class="k">Invoiced · Sep</div><div class="v">£10.8k</div><div class="d up">${ico('trending-up',12)} +22%</div></div><div class="stat"><div class="k">Crew payroll Fri</div><div class="v">£2,120</div><div class="d sea">${ico('users',12)} 4 self-billing</div></div></div>
  <div class="card mt"><div class="hd"><h3>Invoices</h3><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Synced to Xero">${ico('refresh',13)} Sync to Xero</button><button class="btn btn-sm btn-coral" data-act="soon" data-msg="Invoice from job">${ico('plus',13)} New invoice</button></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Invoice</th><th>Client</th><th>Job</th><th>Amount</th><th>Status</th><th>Issued</th><th></th></tr></thead><tbody>${INVOICES.map(i=>`<tr><td><b>${i.id}</b></td><td><div class="thumbcell"><img class="sq" src="${who(i.client).img}" alt=""><b>${who(i.client).n}</b></div></td><td>${i.title}</td><td class="num">${gbp(i.amt)}</td><td><span class="pill ${stPill(i.status)}">${i.status}</span></td><td>${i.when}</td><td><div class="acts">${i.status==='Overdue'?`<button class="btn btn-sm btn-coral" data-act="soon" data-msg="Polite chaser sent to BCP accounts">Chase</button>`:''}<button class="btn btn-sm btn-ghost" data-act="soon">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Payment rules</h3></div><div class="bd">${[['Deposit on acceptance','25% · card or bank transfer'],['Balance','On completion · 14 days'],['Estate contracts','Monthly in arrears · direct debit'],['Storm call-outs','Card on the day']].map(([k,v])=>`<div class="row-item"><div><b>${k}</b><span>${v}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></div>`).join('')}</div></div><div class="card"><div class="hd"><h3>Crew self-billing · this Friday</h3></div><div class="bd">${S.crew.filter(c=>c.status==='On job'||c.who==='priya'||c.who==='callum').slice(0,4).map((c,i)=>`<div class="row-item"><img src="${who(c.who).img}" style="width:36px;height:36px;border-radius:50%;object-fit:cover" alt=""><div><b>${who(c.who).n}</b><span>${[3,2,1,2][i]} days · ${gbp(c.day)}/day</span></div><div class="r"><b>${gbp(c.day*[3,2,1,2][i])}</b></div></div>`).join('')}</div></div></div>`;
ADMIN.pages.settings=()=>`<div class="grid g2">${[['Brand & site','Logo, copy, photos and the services list on the public site.',['Logo uploaded','Service area: Dorset, Hants, Wilts','Domain: militree.co.uk']],['Rate card','Default rates the quote builder pulls from.',['Thinning £1,400 / ha','Felling £480 / day','Planting £2.40 / tree','Storm call-out £640']],['Documents','Templates attached to every quote.',['RAMS template v4','Insurance certs · expire Mar 2027','Terms & conditions']],['One back office, two businesses','Royal Home & Garden shares this calendar, customer list and invoicing.',['Shared calendar: on','Shared customers: on','Separate branding: on']],['Notifications','What lands on your phone.',['New enquiry: WhatsApp + email','Quote viewed: push','Overdue invoice: weekly digest']],['Integrations','Accounting, maps and messaging.',['Xero: connected','WhatsApp Business: connected','what3words: on']]].map(([t,s,items])=>`<div class="card pad"><b style="font-size:1rem">${t}</b><p class="muted" style="font-size:.84rem;margin-top:6px;line-height:1.5">${s}</p><div class="mt">${items.map(i=>`<div class="row-item" style="padding:9px 0"><div style="color:var(--success)">${ico('check-circle',16)}</div><div><b style="font-weight:600">${i}</b></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></div>`).join('')}</div></div>`).join('')}</div>`;
ADMIN.drawer=d=>{ const e=byId(S.enq,d.id); const s=byId(SERVICES,e.svc); const next=['Book survey','Send quote','Schedule job',null][e.col];
  return `<div class="hd"><div><h3>${e.id} · ${COLS[e.col][0]}</h3><div class="muted" style="font-size:.74rem;margin-top:2px">${e.when}</div></div><span class="grow"></span><button class="btn-icon" data-act="drawer-close">${ico('x',16)}</button></div>
  <div class="bd"><div class="row-item" style="border:0"><img src="${who(e.who).img}" style="width:48px;height:48px;border-radius:10px;object-fit:cover" alt=""><div><b>${who(e.who).n}</b><span>${who(e.who).role}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="WhatsApp opened">${ico('message',13)}</button></div></div>
  <h4 class="serif" style="font-size:1.5rem;margin-top:10px">${e.title}</h4><dl class="kv mt"><dt>Service</dt><dd>${s.title}</dd><dt>Location</dt><dd>${e.loc}</dd><dt>Size</dt><dd>${e.size}</dd><dt>Photos</dt><dd>${e.photos||0} attached</dd>${e.survey?`<dt>Survey</dt><dd>${e.survey}</dd>`:''}${e.quote?`<dt>Quote</dt><dd>${gbp(e.quote)}${e.sent?' · sent '+e.sent:''}</dd>`:''}${e.dates?`<dt>Dates</dt><dd>${e.dates}</dd>`:''}</dl>
  ${e.note?`<blockquote style="margin-top:14px;padding:12px 14px;background:var(--sunk);border-radius:12px;font-size:.84rem;line-height:1.55;border-left:3px solid var(--coral)">${e.note}</blockquote>`:''}
  <div class="thumbs" style="margin-top:14px"><img src="${P('forest4')}" alt=""><img src="${P('forest8')}" alt=""><img src="${P('trunk1')}" alt=""></div>
  ${e.col===0?`<div class="field mt2"><label>Survey slot</label><div class="chips">${['Thu 18 Sep · 14:00','Sat 20 Sep · 09:00','Tue 23 Sep · 10:00'].map((x,i)=>`<span class="chip ${i===0?'on':''}">${x}</span>`).join('')}</div></div>`:''}
  ${e.col===2?`<div class="mt2"><span class="pill pill-warn">${ico('eye',10)} Viewed twice · last today 07:52</span></div>`:''}</div>
  <div class="ft"><button class="btn btn-ghost" data-act="soon" data-msg="Note added">${ico('edit',14)} Note</button>${next?`<button class="btn btn-coral" data-act="enq-move" data-id="${e.id}">${ico('arrow-right',14)} ${next}</button>`:`<button class="btn btn-primary" data-act="adm-page" data-p="jobs">Open in calendar</button>`}</div>`; };
