/* MILITREE · public screens */
const SCREENS={}, AFTER={};
const person=k=>PEOPLE[k];
function nav(active,dark){
  return `<nav class="site-nav ${dark?'dark':''}"><a class="brand" data-act="go" data-to="home"><img src="${LOGO}" alt=""><span>Militree Operators<small>Forestry services · Dorset &amp; the South</small></span></a>
    <div class="links">${[['services','Services'],['work','Our work'],['crew','Crew'],['about','About']].map(([r,l])=>`<a data-act="go" data-to="${r}" class="${active===r?'on':''}">${l}</a>`).join('')}</div>
    <div class="right"><a class="${dark?'btn btn-sm btn-light':'btn btn-sm btn-ghost'}" data-act="soon" data-msg="Call 07786 622239">${ico('phone',14)} 07786 622239</a><a class="btn btn-sm btn-coral" data-act="go" data-to="enquiry">Request a site survey</a></div></nav>`;
}
function footer(){ return `<footer class="foot-site"><div class="wrap"><div class="cols"><div><div class="brand"><img src="${LOGO}" alt="">Militree Operators</div><p>Forestry services led by an ex-Royal Marine. Woodland thinning, ancient woodland care, felling, planting and storm response across Dorset, Hampshire and Wiltshire. Fully insured, no recruiter in the middle.</p></div>
  <div><h5>Services</h5>${SERVICES.map(s=>`<a data-act="go" data-to="service" data-id="${s.id}">${s.title}</a>`).join('')}</div>
  <div><h5>Company</h5><a data-act="go" data-to="work">Our work</a><a data-act="go" data-to="about">Credentials &amp; insurance</a><a data-act="go" data-to="crew">Join the crew</a><a data-act="go" data-to="enquiry">Request a survey</a></div>
  <div><h5>Contact</h5><a data-act="soon">07786 622239</a><a data-act="soon">jobs@militree.co.uk</a><a data-act="soon">Wareham, Dorset</a><a data-act="soon">Instagram @militree_operators_forestry</a></div></div>
  <div class="bottom"><span>© 2026 Militree Operators Ltd</span><span>Forestry Commission registered contractor</span><span class="grow"></span><span>Interactive mockup by Nile Technologies</span></div></div></footer>`; }
const svcCard=s=>`<div class="svc" data-act="go" data-to="service" data-id="${s.id}"><div class="n">${ico(s.icon,22)}</div><h3>${s.title}</h3><p>${s.short}</p><div class="tagrow">${s.tags.map(t=>`<span class="pill pill-soft">${t}</span>`).join('')}</div><div class="foot"><span>${s.from}</span><span class="grow"></span>${ico('arrow-right',14)}</div></div>`;
const workCard=w=>`<div class="work" data-act="soon" data-msg="Case study opens: ${w.title}"><img src="${w.img}" alt="">${w.ba?`<div class="ba"><span>Before</span><span class="a">After</span></div>`:''}<div class="cap"><b>${w.title}</b><span>${w.cat} · ${w.loc} · ${w.year}</span></div></div>`;
const howSteps=(on=0)=>`<div class="steps-how">${[['Enquire','Two minutes online. Postcode, what you want, a couple of photos.'],['Survey','Jamie walks the site with you. Usually within a week, free within 30 miles.'],['Quote','Itemised, with the timber credit shown. Accept online, pay a deposit.'],['Scheduled','A named crew, dates in your inbox, photos when it is done.']].map(([t,s],i)=>`<div class="s ${i===on?'on':''}"><div class="n">${i+1}</div><h4>${t}</h4><p>${s}</p></div>`).join('')}</div>`;
const baSlider=()=>`<div class="baslider" style="--cut:${S.cut}%"><img src="${P('forest3')}" alt=""><img class="after" src="${P('forest5')}" alt=""><span class="lab l">Before · 2024</span><span class="lab r">After · 18 months</span><div class="handle"><i>${ico('sliders',18)}</i></div><input type="range" min="5" max="95" value="${S.cut}"></div>`;

SCREENS.home=()=>`${nav('home',true)}
  <section class="hero"><img class="bg" src="${P('forest5')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap">
    <span class="kicker light">Forestry services · Dorset &amp; the South</span><h1>Woodland work <em>done properly.</em></h1>
    <p>Thinning, ancient woodland management, felling, planting and storm response. Led by an ex-Royal Marine with fourteen years in the trees. Fully insured. Straight to us, no recruiter in the middle.</p>
    <div class="cta"><a class="btn btn-lg btn-coral" data-act="go" data-to="enquiry">${ico('clipboard',16)} Request a site survey</a><a class="btn btn-lg btn-light" data-act="go" data-to="work">${ico('image',16)} See our work</a></div>
    <div class="stats"><div class="stat"><div class="v">320 ha</div><div class="k">Managed this year</div></div><div class="stat"><div class="v">14 yrs</div><div class="k">In forestry</div></div><div class="stat"><div class="v">£5m</div><div class="k">Public liability</div></div><div class="stat"><div class="v">48 h</div><div class="k">Quote turnaround</div></div></div>
  </div></div>
  <div class="hside"><div class="next"><span class="k">Next survey slot</span><h4>Thu 18 Sep · Dorset</h4><p>Free site survey within 30 miles of Wareham. Storm call-outs same or next day.</p><div class="row">${ico('map-pin',14)} Dorset · Hants · Wilts</div><div class="row">${ico('shield-check',14)} NPTC certified crew</div><a class="btn btn-block btn-primary" style="margin-top:14px" data-act="go" data-to="enquiry">Book the slot ${ico('arrow-right',14)}</a></div></div></section>
  <div class="stripe"></div>
  <section class="section"><div class="wrap"><div class="sec-head row"><div><span class="kicker">What we do</span><h2>Six services, <em>one crew</em></h2></div><span class="grow"></span><a class="btn btn-ghost" data-act="go" data-to="services">All services ${ico('arrow-right',14)}</a></div><div class="grid g3">${SERVICES.map(svcCard).join('')}</div></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head center"><span class="kicker">How it works</span><h2>Enquiry to <em>crew on site</em> in four steps</h2></div>${howSteps(0)}</div></section>
  <section class="section"><div class="wrap"><div class="split"><div>${baSlider()}</div><div><span class="kicker">Thinning, 18 months on</span><h2>Take out the wrong trees, <em>the wood does the rest</em></h2><p>This is a first thin of a thirty-year-old oak and ash planting. We took the sycamore and the drawn-up stems, left every veteran and every tree with a future. Eighteen months later the floor is green and the crowns have room.</p><ul class="tick-list"><li>${ico('check-circle',18)}<span><b>Marked with you.</b> Nothing comes down that you have not walked past with Jamie.</span></li><li>${ico('check-circle',18)}<span><b>Timber pays.</b> Thinnings stacked at ride-side and sold on your behalf.</span></li><li>${ico('check-circle',18)}<span><b>Licence handled.</b> Felling licence and grant paperwork done for you.</span></li></ul><a class="btn btn-primary mt2" data-act="go" data-to="service" data-id="thin">Woodland thinning ${ico('arrow-right',14)}</a></div></div></div></section>
  <section class="section deep"><div class="wrap"><div class="split"><div><span class="kicker light">Direct, not through a recruiter</span><h2>You pay for <em>the crew,</em> not the middleman</h2><p>Most forestry work in the South is passed through recruitment agencies who take a cut from the client and a cut from the climber. We run our own register of ticketed climbers and operators and put them on your job directly. Same people, better paid, cheaper for you.</p><div class="bigstat"><div><b>0</b><span>Recruiter fees</span></div><div><b>22</b><span>Crew on our register</span></div><div><b>£11k</b><span>Saved for clients this year</span></div></div></div><div class="ph" style="border-radius:var(--r-xl);overflow:hidden;box-shadow:var(--sh-lg);aspect-ratio:5/4"><img src="${P('decor1')}" style="width:100%;height:100%;object-fit:cover" alt=""></div></div></div></section>
  <section class="section"><div class="wrap"><div class="sec-head row"><div><span class="kicker">Recent work</span><h2>On the ground <em>this year</em></h2></div><span class="grow"></span><a class="btn btn-ghost" data-act="go" data-to="work">All projects ${ico('arrow-right',14)}</a></div><div class="grid g3">${WORK.slice(0,3).map(workCard).join('')}</div></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head"><span class="kicker">Credentials</span><h2>Ticketed, insured, <em>accountable</em></h2></div><div class="grid g4">${CERTS.map(([t,s])=>`<div class="cert"><div class="n">${ico('shield-check',18)}</div><div><b>${t}</b><span>${s}</span></div></div>`).join('')}</div></div></section>
  <section class="section"><div class="wrap"><div class="grid g3">${TESTIMONIALS.map(t=>`<div class="quote">${ico('quote',22)}<p>${t.txt}</p><div class="who"><img src="${person(t.who).img}" alt=""><div><b>${t.n}</b><span>Client</span></div></div></div>`).join('')}</div></div></section>
  <section class="section foam"><div class="wrap"><div class="split"><div class="ph wide"><img src="${P('forest1')}" alt=""><div class="float">${ico('hardhat',26)}<div><b>Climbers and operators wanted</b><span>Join the register. Day rates paid direct, no agency cut.</span></div></div></div><div><span class="kicker">Crew</span><h2>Ticketed? <em>Get on the register.</em></h2><p>If you hold CS30/31 and CS38/39 or a LANTRA plant ticket, upload your certs and availability. We match you to jobs by the day and pay you the day rate the client pays for. No agency, no percentage.</p><a class="btn btn-coral mt2" data-act="go" data-to="crew">Join the crew ${ico('arrow-right',14)}</a></div></div></div></section>
  ${footer()}`;

SCREENS.services=()=>`${nav('services')}<section class="pagehero"><img class="bg" src="${P('forestB')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Services</span><h1>Everything from the <em>whip to the veteran</em></h1><p>Planting, thinning, felling, storm response and long-term estate contracts. Every job starts with a walk round the site with Jamie.</p></div></div></section>
  <section class="section"><div class="wrap"><div class="grid g3">${SERVICES.map(svcCard).join('')}</div></div></section>
  <section class="section sunk"><div class="wrap">${howSteps(0)}</div></section>${footer()}`;

SCREENS.service=id=>{ const s=byId(SERVICES,id); const rel=WORK.filter(w=>w.cat.toLowerCase().includes(s.id==='thin'?'thin':s.id==='ancient'?'ancient':s.id==='fell'?'fell':s.id==='plant'?'plant':s.id==='storm'?'storm':'x')).slice(0,3);
  return `${nav('services')}<section class="pagehero" style="min-height:420px"><img class="bg" src="${s.img}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><a class="btn btn-sm btn-light" data-act="go" data-to="services">${ico('arrow-left',13)} All services</a><h1 style="margin-top:18px">${s.title}</h1><p>${s.short}</p><div class="row"><span class="pill pill-dark">${s.from}</span><span class="pill pill-dark">${ico('clock',11)} ${s.dur}</span>${s.tags.map(t=>`<span class="pill pill-dark">${t}</span>`).join('')}</div></div></div></section>
  <section class="section"><div class="wrap"><div class="detail"><div><span class="kicker">The job</span><div class="body"><p style="margin-top:8px">${s.body}</p></div><h3 class="serif" style="font-size:1.8rem;margin-top:36px">What’s included</h3><ul class="tick-list">${s.inc.map(x=>`<li>${ico('check',16)}<span>${x}</span></li>`).join('')}</ul>
    ${rel.length?`<h3 class="serif" style="font-size:1.8rem;margin-top:36px">Recent ${s.title.toLowerCase()} work</h3><div class="grid g3 mt">${rel.map(workCard).join('')}</div>`:''}</div>
    <div class="bookbox"><div class="top"><span class="k">${s.from}</span><div class="when serif" style="font-size:1.6rem">Request a site survey</div><div class="where">Free within 30 miles of Wareham</div></div><div class="bd"><div class="opt on"><span class="n sea">${ico('clipboard',18)}</span><div><b>Site survey</b><span>Jamie walks the site with you, quote within 48 h</span></div><span class="pr">Free</span></div><div class="opt"><span class="n coral">${ico('wind',18)}</span><div><b>Emergency call-out</b><span>Same or next day, make-safe first</span></div><span class="pr">From £640</span></div><a class="btn btn-block btn-lg btn-coral" style="margin-top:14px" data-act="go" data-to="enquiry" data-id="${s.id}">Start the request ${ico('arrow-right',15)}</a><div class="note">${ico('shield',15)}<span>NPTC certified crew, £5m public liability, method statement with every quote.</span></div></div></div></div></div></section>${footer()}`; };

SCREENS.work=()=>{ const cats=['All','Thinning','Ancient woodland','Felling','Planting','Storm']; const list=WORK.filter(w=>S.workFilter==='All'||w.cat===S.workFilter);
  return `${nav('work')}<section class="pagehero" style="min-height:360px"><img class="bg" src="${P('forest7')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Our work</span><h1>Proof, <em>not promises</em></h1><p>Recent projects across Dorset, Hampshire and Wiltshire. Before and after photos on every thinning job.</p></div></div></section>
  <section class="section tight"><div class="wrap"><div class="toolbar"><div class="chips">${cats.map(c=>`<button class="chip ${S.workFilter===c?'on':''}" data-act="work-filter" data-f="${c}">${c}</button>`).join('')}</div></div><div class="grid g3">${list.map(workCard).join('')}</div></div></section>
  <section class="section sunk"><div class="wrap"><div class="split"><div>${baSlider()}</div><div><span class="kicker">Before &amp; after</span><h2>Drag the handle. <em>That is the job.</em></h2><p>Every thinning project gets a fixed-point photo set before, during and eighteen months after. Clients get the full set in their job report.</p></div></div></div></section>${footer()}`; };

SCREENS.about=()=>`${nav('about')}<section class="pagehero"><img class="bg" src="${P('forest2')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">About</span><h1>Marines discipline. <em>Woodsman’s patience.</em></h1><p>Militree Operators is run by Jamie Doxey, eleven years in the Royal Marines and fourteen in forestry. We do not do mass clear-fell. We do the careful work that leaves a woodland better than we found it.</p></div></div></section>
  <section class="section"><div class="wrap"><div class="split"><div class="ph"><img src="${PEOPLE.jamie.img}" alt=""><div class="float">${ico('award',26)}<div><b>Jamie Doxey · Owner &amp; lead climber</b><span>Royal Marines 2005–2016 · NPTC CS30–41 · Summer mountain leader</span></div></div></div><div><span class="kicker">The approach</span><h2>We thin, <em>we don’t strip</em></h2><p>Commercial forestry in this country is mostly about volume. We would rather go into a woodland, take out what is holding it back and leave the veterans to grow for another two hundred years. It is slower, it is better for the wood, and it is what most estates actually want once someone explains the difference.</p><p>Every job is led on site by Jamie. The crew are ticketed climbers and operators from our own register, paid direct.</p></div></div></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head"><span class="kicker">Credentials &amp; insurance</span><h2>Ticketed, insured, <em>accountable</em></h2><p>Certificates and insurance documents are attached to every quote. Ask and we will send them before you book a survey.</p></div><div class="grid g4">${CERTS.map(([t,s])=>`<div class="cert"><div class="n">${ico('shield-check',18)}</div><div><b>${t}</b><span>${s}</span></div><span class="ok">${ico('check-circle',18)}</span></div>`).join('')}</div><div class="grid g3 mt2"><div class="card pad"><b>Method statements</b><p class="muted" style="font-size:.84rem;line-height:1.55;margin-top:6px">A site-specific RAMS document with every quote. Emergency plan, aerial rescue, public exclusion.</p></div><div class="card pad"><b>Felling licences &amp; grants</b><p class="muted" style="font-size:.84rem;line-height:1.55;margin-top:6px">We prepare Forestry Commission felling licence applications and EWCO / Countryside Stewardship claims on your behalf.</p></div><div class="card pad"><b>Where we work</b><p class="muted" style="font-size:.84rem;line-height:1.55;margin-top:6px">Based in Wareham. Dorset, Hampshire and Wiltshire as standard. Further for estate contracts and storm response.</p></div></div></div></section>
  <section class="section"><div class="wrap"><div class="sec-head"><span class="kicker">Regular crew</span><h2>The people <em>in the trees</em></h2></div><div class="grid g3">${S.crew.slice(0,6).map(c=>`<div class="crewcard"><img src="${person(c.who).img}" alt=""><div><b>${person(c.who).n}</b><div class="role">${person(c.who).role}</div><div class="tix">${c.tix.map(t=>`<span class="pill pill-navy">${t}</span>`).join('')}</div></div></div>`).join('')}</div></div></section>${footer()}`;

/* ---------- enquiry wizard ---------- */
SCREENS.enquiry=()=>{ const w=S.wiz; const s=byId(SERVICES,w.svc); const steps=['What you need','Where & how big','Photos & access','Your details'];
  const stepHTML=`<div class="steps">${steps.map((t,i)=>`<div class="st ${w.step===i+1?'on':w.step>i+1?'done':''}"><i>${w.step>i+1?ico('check',12):i+1}</i>${t}</div>${i<steps.length-1?'<span class="ln"></span>':''}`).join('')}</div>`;
  let panel='';
  if(w.step===1) panel=`<div class="panel"><h2>What do you need?</h2><p>Pick the closest. Jamie will refine it on the survey.</p><div class="radio-cards mt2" style="grid-template-columns:1fr 1fr">${SERVICES.map(x=>`<div class="rcard ${w.svc===x.id?'on':''}" data-act="wiz-svc" data-id="${x.id}"><span class="dot"></span><div><b>${x.title}</b><span>${x.short}</span></div><span class="pr">${x.from}</span></div>`).join('')}</div><div class="acts"><a class="btn btn-ghost" data-act="go" data-to="home">Cancel</a><button class="btn btn-primary" data-act="wiz-next">Continue ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===2) panel=`<div class="panel"><h2>Where is it and how big?</h2><p>A postcode is enough. Draw the area if you can, or guess and we will measure on the survey.</p><div class="form"><div class="field"><label>Postcode</label><input class="input" value="BH18 9AB"></div><div class="field"><label>Approximate size</label><select class="select"><option>Under 1 ha (a couple of acres)</option><option selected>1 – 5 ha</option><option>5 – 20 ha</option><option>20 ha +</option><option>A single tree or a few trees</option></select></div><div class="field full"><div class="mapbox"><img src="${P('fell1')}" alt=""><div class="area"></div><span class="pin">${ico('map-pin',36)}</span><div class="lbl">${ico('map-pin',13)} Broadstone BH18 · approx. 2.1 ha drawn</div></div></div><div class="field"><label>Who owns it?</label><select class="select"><option>Me</option><option>An estate I manage</option><option>A trust, charity or council</option><option>Not sure</option></select></div><div class="field"><label>Any designations?</label><select class="select"><option>Not that I know of</option><option>Ancient woodland / SSSI</option><option>TPO or conservation area</option></select></div></div><div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-primary" data-act="wiz-next">Continue ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===3) panel=`<div class="panel"><h2>Photos &amp; access</h2><p>A few phone photos save a wasted visit. Access tells us what kit to bring.</p><div class="form"><div class="field full"><div class="upload">${ico('camera',28)}<b>Drop photos here or tap to take some</b>Up to 10 · phone photos are fine</div><div class="thumbs"><img src="${P('forest4')}" alt=""><img src="${P('forest8')}" alt=""><img src="${P('trunk1')}" alt=""></div></div><div class="field"><label>Vehicle access</label><select class="select"><option>Track suitable for a 4x4 and trailer</option><option>Tarmac road only</option><option>On foot only</option><option>Not sure</option></select></div><div class="field"><label>Timing</label><select class="select"><option>No rush · next few months</option><option>Before winter</option><option>Urgent · dangerous tree</option></select></div><div class="field full"><label>Anything else</label><textarea class="textarea">Not touched in 20 years. Want light back to the garden but keep it a wood. Neighbours on the east side.</textarea></div></div><div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-primary" data-act="wiz-next">Continue ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===4) panel=`<div class="panel"><h2>Your details</h2><p>Jamie will call to book the survey. Usually the same day.</p><div class="form"><div class="field"><label>Name</label><input class="input" value="Sarah Pemberton"></div><div class="field"><label>Mobile</label><input class="input" value="07700 900 456"></div><div class="field full"><label>Email</label><input class="input" value="sarah.p@example.com"></div><div class="field full"><label>Preferred survey slot</label><div class="chips">${['Thu 18 Sep · AM','Thu 18 Sep · PM','Sat 20 Sep · AM','Any weekday'].map((x,i)=>`<span class="chip ${i===1?'on':''}">${x}</span>`).join('')}</div></div><label class="check full"><input type="checkbox" checked> Send me the quote by email and WhatsApp</label></div><div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-coral btn-lg" data-act="wiz-finish">${ico('send',14)} Send survey request</button></div></div>`;
  else panel=`<div class="panel"><div class="confirm"><div class="ring">${ico('check',40)}</div><h2>Request ${w.ref} received</h2><p>Jamie has it on his phone. You will get a call to confirm Thursday afternoon’s survey, then an itemised quote within 48 hours of the visit.</p><div class="unlocked"><div class="u">${ico('calendar',20)}<div><b>Survey · Thu 18 Sep · PM</b><span>Pending Jamie’s confirmation</span></div></div><div class="u">${ico('file-text',20)}<div><b>Quote within 48 h</b><span>Itemised · timber credit shown</span></div></div><div class="u">${ico('message',20)}<div><b>Updates by WhatsApp</b><span>07700 900 456</span></div></div></div><div class="acts"><a class="btn btn-primary" data-act="go" data-to="quote">See a sample quote</a><a class="btn btn-ghost" data-act="go" data-to="home">Back to site</a></div></div></div>`;
  return `${nav('enquiry')}<section class="section tight" style="padding-top:34px"><div class="wrap">${w.step<5?stepHTML:''}<div class="wizard">${panel}<div class="summary"><span class="k">Site survey request</span><h4>${s.title}</h4><div class="row" style="margin-top:14px"><span>Survey</span><span>Free within 30 miles</span></div><div class="row"><span>Guide price</span><span>${s.from}</span></div><div class="row"><span>Typical duration</span><span>${s.dur}</span></div><div class="row"><span>Quote</span><span>Within 48 h of survey</span></div><div class="impact-note">${ico('shield-check',16)}<span>Every quote comes with a method statement, certificates and insurance documents attached.</span></div></div></div></div></section>${footer()}`; };

/* ---------- client quote view ---------- */
SCREENS.quote=()=>{ const q=QUOTE; const st=S.quote.state; const c=person(q.client);
  const acts=st==='sent'?`<button class="btn btn-block btn-lg btn-coral" data-act="quote-accept">Accept quote &amp; pay deposit ${ico('arrow-right',15)}</button><button class="btn btn-block btn-ghost mt" data-act="soon" data-msg="Question sent to Jamie">${ico('message',14)} Ask a question</button>`:
    st==='accepting'?`<div class="paycard"><div class="field"><label>Card number</label><input class="input" value="4242 4242 4242 4242"></div><div class="row2"><div class="field"><label>Expiry</label><input class="input" value="09 / 28"></div><div class="field"><label>CVC</label><input class="input" value="123"></div></div></div><label class="check mt"><input type="checkbox" checked> I accept the quote, method statement and terms</label><button class="btn btn-block btn-lg btn-coral mt" data-act="quote-pay">${ico('lock',14)} Pay ${gbp(q.deposit)} deposit</button><button class="btn btn-block btn-ghost mt" data-act="soon" data-msg="Bank transfer details emailed">Pay by bank transfer instead</button>`:
    `<div class="confirm" style="padding:10px 0"><div class="ring" style="width:64px;height:64px">${ico('check',30)}</div><h2 style="font-size:1.6rem">Accepted</h2><p style="font-size:.86rem">Deposit received. Jamie will confirm the crew and start date within 24 hours. Balance due on completion.</p></div>`;
  return `${nav('quote')}<section class="section tight" style="padding-top:34px"><div class="wrap"><div class="pagehead"><div><span class="kicker">Quote ${q.id} · ${st==='accepted'?'Accepted':'Awaiting your decision'}</span><h2 class="serif" style="font-size:2.4rem;margin-top:4px">${q.title}</h2><p>Prepared for ${c.n} · ${q.valid}</p></div><span class="grow"></span><button class="btn btn-ghost" data-act="soon" data-msg="PDF downloaded">${ico('download',14)} PDF</button></div>
    <div class="detail mt"><div><div class="card"><div class="hd"><h3>Itemised quote</h3><span class="grow"></span><span class="pill pill-sea">Timber credit included</span></div><div class="bd"><div class="quotehead"><span>Item</span><span>Qty</span><span class="num">Rate</span><span class="num">Total</span></div>${q.lines.map(([t,qy,r,tt])=>`<div class="quoteline"><div><b>${t}</b></div><span>${qy}</span><span class="num">${r<0?'−':''}${gbp2(Math.abs(r))}</span><span class="num" style="${tt<0?'color:var(--success)':''}">${tt<0?'−':''}${gbp(Math.abs(tt))}</span></div>`).join('')}<div class="quoteline" style="border:0"><div></div><span></span><span class="num muted">Subtotal</span><span class="num">${gbp(q.sub)}</span></div><div class="quoteline" style="border:0;padding-top:0"><div></div><span></span><span class="num muted">VAT 20%</span><span class="num">${gbp(q.vat)}</span></div><div class="quoteline" style="border:0;padding-top:0;font-size:1.05rem"><div></div><span></span><span class="num"><b>Total</b></span><span class="num"><b>${gbp(q.tot)}</b></span></div></div></div>
      <div class="grid g3 mt"><div class="stat"><div class="k">Start</div><div class="v" style="font-size:1.2rem">${q.start}</div></div><div class="stat"><div class="k">Duration</div><div class="v" style="font-size:1.2rem">${q.dur}</div></div><div class="stat"><div class="k">Crew</div><div class="v" style="font-size:1.2rem">${q.crew}</div></div></div>
      <div class="card mt"><div class="hd"><h3>Attached</h3></div><div class="bd"><div class="grid g2">${[['file-text','Method statement & risk assessment','RAMS-0412 · 6 pages'],['shield-check','Insurance certificates','£5m PL · EL · hired-in plant'],['award','NPTC certificates · crew of 4','CS30/31/38/39/41'],['map-pin','Marked-tree map','Walked with you on 9 Sep']].map(([i,t,s])=>`<div class="resource">${ico(i,20)}<div><b>${t}</b><span>${s}</span></div></div>`).join('')}</div></div></div></div>
      <div class="bookbox"><div class="top"><span class="k">${st==='accepted'?'Paid':'To accept'}</span><div class="when serif" style="font-size:1.8rem">${gbp(q.deposit)} deposit</div><div class="where">25% · balance ${gbp(q.tot-q.deposit)} on completion</div></div><div class="bd">${acts}<div class="note">${ico('info',15)}<span>Deposit is refundable up to 14 days before start. Weather delays never cost you.</span></div></div></div></div></div></section>${footer()}`; };

/* ---------- crew register (public) ---------- */
SCREENS.crew=()=>`${nav('crew')}<section class="pagehero"><img class="bg" src="${P('forest1')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Crew register</span><h1>Ticketed? <em>Get paid direct.</em></h1><p>Climbers, groundworkers and plant operators. Upload your tickets and availability once. We match you to jobs by the day and pay you the client’s day rate with nothing skimmed off.</p></div></div></section>
  <section class="section"><div class="wrap"><div class="split"><div><span class="kicker">How it works</span><h2>No agency. <em>No percentage.</em></h2><ul class="tick-list">${[['Register once','Tickets, first aid, insurance, availability. Five minutes.'],['Get offered days','Jobs near you land on your phone. Accept or decline, no pressure.'],['Turn up, do the job','Named lead on site, RAMS in your inbox the night before.'],['Paid weekly','Day rate paid direct every Friday. Self-billing invoices generated for you.']].map(([b,s])=>`<li>${ico('check-circle',18)}<span><b>${b}.</b> ${s}</span></li>`).join('')}</ul><div class="bigstat" style="margin-top:26px"><div><b style="color:var(--coral)">£260</b><span style="color:var(--ink-3)">Climber day rate</span></div><div><b style="color:var(--coral)">£200</b><span style="color:var(--ink-3)">Ground day rate</span></div><div><b style="color:var(--coral)">Fri</b><span style="color:var(--ink-3)">Paid weekly</span></div></div></div>
    <div class="card pad"><h3 class="serif" style="font-size:1.8rem">Register</h3><div class="form" style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px"><div class="field"><label>Name</label><input class="input" placeholder="Full name"></div><div class="field"><label>Mobile</label><input class="input" placeholder="07…"></div><div class="field"><label>Role</label><select class="select"><option>Climber</option><option>Groundworker</option><option>Machine operator</option><option>Forestry lead</option></select></div><div class="field"><label>Base postcode</label><input class="input" placeholder="BH20"></div><div class="field" style="grid-column:1/-1"><label>Tickets</label><div class="chips">${['CS30/31','CS38/39','CS41','MEWP','LANTRA chipper','LANTRA forwarder','First Aid +F','Rigging'].map((t,i)=>`<span class="chip ${[0,1,6].includes(i)?'on':''}">${t}</span>`).join('')}</div></div><div class="field" style="grid-column:1/-1"><div class="upload">${ico('upload',24)}<b>Upload certificates</b>Photos or PDFs · we verify against NPTC</div></div><div class="field" style="grid-column:1/-1"><label>Availability</label><div class="chips">${['Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<span class="chip ${i<5?'on':''}">${d}</span>`).join('')}</div></div></div><button class="btn btn-coral btn-block btn-lg mt2" data-act="soon" data-msg="Application sent · Jamie will call within 2 days">${ico('user-plus',15)} Apply to the register</button></div></div></div></section>${footer()}`;
