/* ROYAL · public screens */
const SCREENS={};
const person=k=>PEOPLE[k];
const stars=n=>`<span class="stars">${Array.from({length:5},(_,i)=>ico(i<n?'star-fill':'star',14,i<n?'':'muted')).join('')}</span>`;
function nav(active,dark){ return `<nav class="site-nav ${dark?'dark':''}"><a class="brand" data-act="go" data-to="home"><img src="${LOGO}" alt=""><span>Royal Home &amp; Garden<small>Handyman · Garden · Decorating · Purbeck &amp; Poole</small></span></a>
  <div class="links">${[['services','Price list'],['quote','Photo quote'],['reviews','Reviews'],['about','About']].map(([r,l])=>`<a data-act="go" data-to="${r}" class="${active===r?'on':''}">${l}</a>`).join('')}</div>
  <div class="right"><a class="btn btn-sm ${dark?'btn-light':'btn-ghost'}" data-act="soon" data-msg="Call 07786 622239">${ico('phone',14)} 07786 622239</a><a class="avatar" data-act="go" data-to="myjobs"><img src="${PEOPLE.me.img}" alt="">${PEOPLE.me.first}</a><a class="btn btn-sm btn-coral" data-act="go" data-to="book">Book a slot</a></div></nav>`; }
function footer(){ return `<footer class="foot-site"><div class="wrap"><div class="cols"><div><div class="brand"><img src="${LOGO}" alt="">Royal Home &amp; Garden Services</div><p>Lawns, hedges, fences, painting, handyman jobs and access ramps across Purbeck and Poole. Book online, pay on the day or by card. Special rate for over-65s, always.</p></div>
  <div><h5>Book</h5><a data-act="go" data-to="book">Book a slot</a><a data-act="go" data-to="services">Price list</a><a data-act="go" data-to="quote">Photo quote</a><a data-act="go" data-to="myjobs">My jobs</a></div><div><h5>Company</h5><a data-act="go" data-to="reviews">Reviews &amp; areas</a><a data-act="go" data-to="about">About Jamie</a><a href="../militree/index.html">Big trees? Militree Operators</a></div><div><h5>Contact</h5><a data-act="soon">07786 622239</a><a data-act="soon">hello@royalhomeandgarden.co.uk</a><a data-act="soon">Swanage, Dorset</a><a data-act="soon">Instagram @royal_homengarden_services</a></div></div>
  <div class="bottom"><span>© 2026 Royal Home &amp; Garden Services</span><span>Fully insured · DBS checked</span><span class="grow"></span><span>Interactive mockup by Nile Technologies</span></div></div></footer>`; }
const oapBadge=()=>`<span class="oap"><span class="n">65+</span> Special rate for over-65s · 15% off every job</span>`;
const menuItem=i=>`<div class="menu-item" data-act="${i.price?'book-item':'go'}" ${i.price?`data-id="${i.id}"`:`data-to="quote" data-id="${i.id}"`}><div class="n ${i.plan?'gold':i.price?'':'purple'}">${ico(i.plan?'refresh':i.price?'calendar':'camera',22)}</div><div><b>${i.title}</b><span>${i.short}</span></div><div class="pr">${i.price?`<b>${gbp(i.price)}</b><small>${i.unit}</small>`:`<b>Quote</b><small>from photos</small>`}</div><span class="go">${ico('chevron-right',18)}</span></div>`;

SCREENS.home=()=>{ const top=[byId(ALL_ITEMS,'mow'),byId(ALL_ITEMS,'hedge'),byId(ALL_ITEMS,'fence'),byId(ALL_ITEMS,'room'),byId(ALL_ITEMS,'handy'),byId(ALL_ITEMS,'ramp')];
  return `${nav('home',true)}<section class="hero" style="min-height:82vh"><img class="bg" src="${P('hs2')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Handyman · Garden · Decorating · Purbeck &amp; Poole</span><h1>Your home and garden, <em>sorted.</em></h1><p>Lawns, hedges, fences, painting, small fixes and access ramps. Pick a job, pick a slot, Jamie turns up. Book it online like a barber, pay on the day or by card.</p><div class="cta"><a class="btn btn-lg btn-coral" data-act="go" data-to="book">${ico('calendar',16)} Book a slot</a><a class="btn btn-lg btn-light" data-act="go" data-to="quote">${ico('camera',16)} Get a photo quote</a></div><div class="stats"><div class="stat"><div class="v">4.9</div><div class="k">212 reviews</div></div><div class="stat"><div class="v">Thu</div><div class="k">Next free slot</div></div><div class="stat"><div class="v">15%</div><div class="k">Off for over-65s</div></div><div class="stat"><div class="v">1,400</div><div class="k">Jobs done</div></div></div></div></div>
  <div class="hside"><div class="next"><span class="k">Next free slots</span><h4>This week</h4><div class="slots" style="grid-template-columns:repeat(4,1fr);margin-top:10px">${DAYS.slice(0,4).map((d,i)=>`<div class="d ${d[3]===0?'off':i===2?'on':''}" data-act="go" data-to="book"><b>${d[1]}</b><span>${d[0]}</span><i>${d[3]?d[3]+' free':'Full'}</i></div>`).join('')}</div><a class="btn btn-block btn-primary" style="margin-top:14px" data-act="go" data-to="book">Grab a slot ${ico('arrow-right',14)}</a></div></div></section>
  <section class="section tight" style="padding:26px 0"><div class="wrap" style="display:flex;align-items:center;gap:18px;flex-wrap:wrap">${oapBadge()}<span class="muted" style="font-size:.86rem">Tick the box when you book. No proof needed, we trust you.</span><span class="grow"></span><span class="areas">${AREAS.slice(0,5).map(a=>`<span>${ico('map-pin',12)} ${a}</span>`).join('')}</span></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head row"><div><span class="kicker">Price list</span><h2>Prices up front, <em>no surprises</em></h2><p>Most jobs have a fixed price. The rest get a quote from a couple of phone photos, usually within the hour.</p></div><span class="grow"></span><a class="btn btn-ghost" data-act="go" data-to="services">Full price list ${ico('arrow-right',14)}</a></div><div class="grid g2">${top.map(menuItem).join('')}</div></div></section>
  <section class="section"><div class="wrap"><div class="sec-head center"><span class="kicker">How it works</span><h2>Booked in <em>two minutes</em></h2></div><div class="grid g4">${[['list','Pick the job','Fixed price from the list, or send photos for a quote.'],['calendar','Pick a slot','Live availability. Morning or afternoon, this week or next.'],['navigation','Jamie turns up','You get a text when he is on his way with an ETA.'],['card','Pay how you like','Card on the app, or cash on the day. Invoice by email.']].map(([i,t,s])=>`<div class="card pad"><div style="width:48px;height:48px;border-radius:16px;background:var(--sea-tint);color:var(--sea);display:grid;place-items:center">${ico(i,22)}</div><b style="display:block;margin-top:14px;font-family:var(--serif);font-size:1.15rem">${t}</b><p class="muted" style="font-size:.86rem;line-height:1.55;margin-top:6px">${s}</p></div>`).join('')}</div></div></section>
  <section class="section foam"><div class="wrap"><div class="split"><div class="ph wide"><img src="${P('garden2')}" alt=""><div class="float">${ico('refresh',26)}<div><b>Garden care plan · £89 a month</b><span>Fortnightly visit, mow, edge, borders. Cancel any time.</span></div></div></div><div><span class="kicker">Regular visits</span><h2>Set it up once, <em>forget about it</em></h2><p>Fortnightly lawn and garden visits on a monthly plan. Same day, same time, same Jamie. Hedges in season, leaves in autumn. Pause it when you are away.</p><ul class="tick-list"><li>${ico('check-circle',18)}<span><b>Fortnightly visit.</b> Mow, edge, borders, tidy.</span></li><li>${ico('check-circle',18)}<span><b>Seasonal extras included.</b> Hedges twice a year, leaf clearance in autumn.</span></li><li>${ico('check-circle',18)}<span><b>Over-65 rate £76.</b> Same plan, pensioner price.</span></li></ul><a class="btn btn-primary mt2" data-act="book-item" data-id="care">Start a care plan ${ico('arrow-right',14)}</a></div></div></div></section>
  <section class="section"><div class="wrap"><div class="split"><div><span class="kicker">Not on the list?</span><h2>Send a photo, <em>get a price</em></h2><p>Peeling paint, a leaking gutter, a bathroom that needs re-sealing. Take two photos on your phone, tell us what you want, and Jamie sends a price back, usually within the hour. Accept it and pick a slot.</p><a class="btn btn-coral mt2" data-act="go" data-to="quote">${ico('camera',15)} Get a photo quote</a></div><div class="ph"><img src="${P('hm1')}" alt=""><div class="float">${ico('clock',26)}<div><b>Average reply: 48 minutes</b><span>During working hours</span></div></div></div></div></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head row"><div><span class="kicker">Reviews</span><h2>What the neighbours <em>say</em></h2></div><span class="grow"></span><div style="display:flex;align-items:center;gap:8px;font-weight:700">${stars(5)} 4.9 · 212 Google reviews</div></div><div class="grid g4">${REVIEWS.map(r=>`<div class="review">${stars(r.stars)}<p>${r.txt}</p><div class="who"><img src="${person(r.who).img}" alt=""><div><b>${person(r.who).n}</b><span>${person(r.who).role.split(' · ')[1]}</span></div></div></div>`).join('')}</div></div></section>
  <section class="section deep"><div class="wrap"><div class="split"><div><span class="kicker light">Two businesses, one Jamie</span><h2>Big trees? <em>That’s the other van.</em></h2><p>Royal Home &amp; Garden handles the house and the garden. Anything over about eight metres, woodland, or a tree near a building goes to our forestry business, Militree Operators, with the same booking and the same person on the other end of the phone.</p><a class="btn btn-white mt2" href="../militree/index.html">Militree Operators ${ico('arrow-up-right',14)}</a></div><div class="ph" style="border-radius:var(--r-xl);overflow:hidden;box-shadow:var(--sh-lg);aspect-ratio:5/4"><img src="${P('forest6')}" style="width:100%;height:100%;object-fit:cover" alt=""></div></div></div></section>${footer()}`; };

SCREENS.services=()=>`${nav('services')}<section class="pagehero" style="min-height:340px"><img class="bg" src="${P('garden3')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Price list</span><h1>Every job, <em>every price</em></h1><p>Fixed prices where we can, photo quotes where we can’t. Over-65s get 15% off everything except the care plan, which has its own pensioner price.</p><div class="row">${oapBadge()}</div></div></div></section>
  <section class="section tight"><div class="wrap">${CATS.map(c=>`<div class="catgroup"><h3>${ico(c.icon,22)} ${c.title}</h3><div class="grid g2">${c.items.map(menuItem).join('')}</div></div>`).join('')}</div></section>${footer()}`;

SCREENS.book=()=>{ const w=S.wiz; const it=byId(ALL_ITEMS,w.item); const day=DAYS[w.day]; const price=priceOf(it,w.oap,w.size); const steps=['Job','Details','Slot','You','Pay'];
  const stepHTML=`<div class="steps">${steps.map((t,i)=>`<div class="st ${w.step===i+1?'on':w.step>i+1?'done':''}"><i>${w.step>i+1?ico('check',12):i+1}</i>${t}</div>${i<steps.length-1?'<span class="ln"></span>':''}`).join('')}</div>`;
  let panel='';
  if(w.step===1) panel=`<div class="panel"><h2>What needs doing?</h2><p>Pick from the list. Not there? Send a photo instead.</p>${CATS.map(c=>`<div class="catgroup" style="margin-top:22px"><h3 style="font-size:1.1rem">${ico(c.icon,18)} ${c.title}</h3><div class="grid" style="gap:10px">${c.items.filter(i=>i.price).map(menuItem).join('')}</div></div>`).join('')}</div>`;
  else if(w.step===2) panel=`<div class="panel"><h2>${it.title}</h2><p>${it.short}</p><div class="form">${it.id==='mow'?`<div class="field full"><label>Lawn size</label><div class="chips">${['Small (under 100 m²)','Medium (100–200 m²)','Large (200–400 m²)'].map(x=>`<span class="chip ${w.size===x?'on':''}" data-act="wiz-size" data-v="${x}">${x}</span>`).join('')}</div></div>`:it.id==='fence'?`<div class="field"><label>Panels</label><select class="select"><option>1</option><option selected>2</option><option>3</option><option>4+</option></select></div><div class="field"><label>Posts</label><select class="select"><option>Posts are fine</option><option>1 post needs replacing (+£45)</option><option>Not sure</option></select></div>`:it.id==='room'?`<div class="field"><label>Room</label><select class="select"><option>Lounge</option><option>Bedroom</option><option>Kitchen</option><option>Hall & stairs (+£60)</option></select></div><div class="field"><label>Paint</label><select class="select"><option>I’ll supply</option><option>Jamie supplies (+cost)</option></select></div>`:`<div class="field full"><label>Tell us a bit more</label><textarea class="textarea" placeholder="Anything Jamie should know"></textarea></div>`}
    <div class="field full"><div class="upload">${ico('camera',24)}<b>Add a photo (optional)</b>Helps Jamie bring the right kit</div></div>
    ${it.recur?`<div class="rcard full ${w.recur?'on':''}" data-act="wiz-recur"><span class="dot"></span><div><b>Make it fortnightly</b><span>Same slot every two weeks. Cancel or pause any time. Saves £5 a visit.</span></div><span class="pr">${it.plan?'':'−£5'}</span></div>`:''}
    <div class="rcard full ${w.oap?'on':''}" data-act="wiz-oap"><span class="dot"></span><div><b>I’m over 65</b><span>15% off, no proof needed.</span></div><span class="pr">−15%</span></div></div>
    <div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-primary" data-act="wiz-next">Pick a slot ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===3) panel=`<div class="panel"><h2>Pick a slot</h2><p>Live availability. Grey days are full.</p><div class="slots mt2">${DAYS.map((d,i)=>`<div class="d ${d[3]===0?'off':w.day===i?'on':''}" data-act="wiz-day" data-i="${i}"><b>${d[1]}</b><span>${d[0]} ${d[2]}</span><i>${d[3]?d[3]+' free':'Full'}</i></div>`).join('')}</div><div class="times">${TIMES.map((t,i)=>`<div class="t ${w.time===i?'on':''} ${!t[2]?'off':''}" data-act="wiz-time" data-i="${i}">${t[0]}<span>${t[1]}${!t[2]?' · taken':''}</span></div>`).join('')}</div><div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-primary" data-act="wiz-next">Continue ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===4) panel=`<div class="panel"><h2>Where and who</h2><p>So Jamie can find you and text you when he is on his way.</p><div class="form"><div class="field"><label>Name</label><input class="input" value="${PEOPLE.me.n}"></div><div class="field"><label>Mobile</label><input class="input" value="07700 900 321"></div><div class="field full"><label>Address</label><input class="input" value="${PEOPLE.me.addr}"></div><div class="field"><label>Access</label><select class="select"><option>Side gate, unlocked</option><option>I’ll be in</option><option>Key safe (I’ll text the code)</option></select></div><div class="field"><label>Parking</label><select class="select"><option>On the drive</option><option>On the road</option><option>Permit needed</option></select></div><label class="check full"><input type="checkbox" checked> Text me when Jamie is on his way</label></div><div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-primary" data-act="wiz-next">Continue ${ico('arrow-right',14)}</button></div></div>`;
  else if(w.step===5) panel=`<div class="panel"><h2>How would you like to pay?</h2><p>No deposit for fixed-price jobs under £150.</p><div class="radio-cards mt2"><div class="rcard ${w.pay==='day'?'on':''}" data-act="wiz-pay" data-m="day"><span class="dot"></span><div><b>Pay on the day</b><span>Cash, or tap your card on Jamie’s reader when he’s done.</span></div></div><div class="rcard ${w.pay==='now'?'on':''}" data-act="wiz-pay" data-m="now"><span class="dot"></span><div><b>Pay now by card</b><span>Nothing to do on the day. Refunded in full if we cancel.</span></div></div></div>${w.pay==='now'?`<div class="paycard mt"><div class="field"><label>Card number</label><input class="input" value="4242 4242 4242 4242"></div><div class="row2"><div class="field"><label>Expiry</label><input class="input" value="09 / 28"></div><div class="field"><label>CVC</label><input class="input" value="123"></div></div></div>`:''}<div class="acts"><button class="btn btn-ghost" data-act="wiz-back">Back</button><button class="btn btn-coral btn-lg" data-act="wiz-finish">${ico(w.pay==='now'?'lock':'check',14)} ${w.pay==='now'?'Pay '+gbp(price)+' & book':'Confirm booking'}</button></div></div>`;
  else panel=`<div class="panel"><div class="confirm"><div class="ring">${ico('check',40)}</div><h2>Booked · ${w.ref}</h2><p>${it.title} on ${day[0]} ${day[1]} ${day[2]} at ${TIMES[w.time][0]}. Confirmation texted to 07700 900 321. Jamie will text again when he is on his way.</p><div class="unlocked"><div class="u">${ico('calendar',20)}<div><b>Add to calendar</b><span>Google · Apple · Outlook</span></div></div><div class="u">${ico('navigation',20)}<div><b>On-my-way text</b><span>With live ETA</span></div></div><div class="u">${ico('refresh',20)}<div><b>${w.recur?'Repeats fortnightly':'Book it again'}</b><span>${w.recur?'Pause any time':'One tap from My jobs'}</span></div></div></div><div class="acts"><a class="btn btn-primary" data-act="go" data-to="myjobs">See my jobs</a><a class="btn btn-ghost" data-act="go" data-to="home">Done</a></div></div></div>`;
  return `${nav('book')}<section class="section tight" style="padding-top:34px"><div class="wrap">${w.step<6?stepHTML:''}<div class="wizard">${panel}<div class="summary"><span class="k">Your booking</span><h4>${w.step===1?'Pick a job':it.title}</h4>${w.step>1?`<div class="row" style="margin-top:14px"><span>When</span><span>${w.step>=3?day[0]+' '+day[1]+' '+day[2]+' · '+TIMES[w.time][0]:'Choose a slot'}</span></div><div class="row"><span>Takes about</span><span>${it.dur?Math.round(it.dur/60*10)/10+' h':'—'}</span></div><div class="row"><span>${it.title}</span><span>${gbp(it.price)}${it.id==='fence'?' × 2':''}</span></div>${w.oap&&!it.plan?`<div class="row"><span>Over-65 rate</span><span>−15%</span></div>`:''}${w.recur&&!it.plan?`<div class="row"><span>Fortnightly saving</span><span>−£5</span></div>`:''}<div class="row total"><span>${it.plan?'Per month':'Total'}</span><span>${gbp(it.plan?(w.oap?76:89):price-(w.recur?5:0))}</span></div>`:`<div class="row" style="margin-top:14px"><span>Fixed price</span><span>Shown up front</span></div><div class="row"><span>Over-65s</span><span>15% off</span></div>`}<div class="impact-note">${ico('shield-check',16)}<span>Fully insured, DBS checked, 4.9 from 212 reviews. Cancel free up to 24 h before.</span></div></div></div></div></section>${footer()}`; };

SCREENS.quote=()=>{ const st=S.pq.state; const it=byId(ALL_ITEMS,S.pq.item||'extpaint')||ALL_ITEMS[0];
  return `${nav('quote')}<section class="section tight" style="padding-top:34px"><div class="wrap"><div class="pagehead"><div><span class="kicker">Photo quote</span><h2 class="serif" style="font-size:2.2rem;margin-top:4px">Send a photo, <em style="color:var(--sea)">get a price</em></h2><p>Usually back within the hour during working hours. Accept it and you go straight to picking a slot.</p></div></div>
    <div class="wizard mt">${st==='form'?`<div class="panel"><div class="form"><div class="field full"><div class="upload">${ico('camera',30)}<b>Take or drop photos here</b>Two or three from different angles is perfect</div><div class="thumbs"><img src="${P('house1')}" alt=""><img src="${P('hm4')}" alt=""><img src="${P('paint1')}" alt=""></div></div><div class="field"><label>What kind of job?</label><select class="select"><option ${it.id==='extpaint'?'selected':''}>Exterior painting</option><option ${it.id==='bath'?'selected':''}>Bathroom refresh</option><option>Something else</option></select></div><div class="field"><label>Rough timing</label><select class="select"><option>Next couple of weeks</option><option>This week if possible</option><option>No rush</option></select></div><div class="field full"><label>What do you want done?</label><textarea class="textarea">Front fascias and the front door. Paint is peeling on the south side, wood looks OK underneath.</textarea></div><div class="field"><label>Name</label><input class="input" value="${PEOPLE.me.n}"></div><div class="field"><label>Mobile</label><input class="input" value="07700 900 321"></div><label class="check full"><input type="checkbox" checked> I’m over 65 (15% off)</label></div><div class="acts"><button class="btn btn-coral btn-lg" data-act="pq-submit">${ico('send',14)} Send for a quote</button></div></div>`:
    `<div class="panel"><div class="confirm"><div class="ring">${ico('send',40)}</div><h2>Photos sent</h2><p>Jamie has them on his phone. You will get a price by text and email, usually within the hour. Accept it and pick a slot in one tap.</p><div class="acts"><a class="btn btn-primary" data-act="go" data-to="myjobs">My jobs</a><a class="btn btn-ghost" data-act="go" data-to="home">Back home</a></div></div></div>`}
    <div class="summary"><span class="k">How it works</span><h4>Three steps</h4><div class="row" style="margin-top:14px"><span>1</span><span>Send photos &amp; a line or two</span></div><div class="row"><span>2</span><span>Price back within the hour</span></div><div class="row"><span>3</span><span>Accept &amp; pick a slot</span></div><div class="impact-note">${ico('clock',16)}<span>Average reply this month: 48 minutes. Quotes are fixed once accepted, no “it turned out bigger”.</span></div></div></div></div></section>${footer()}`; };

SCREENS.myjobs=()=>{ const mine=S.bookings.filter(b=>b.who==='me'); const next=mine[0]; const it=next?byId(ALL_ITEMS,next.item):null; const t=S.acct;
  const row=b=>{ const i=byId(ALL_ITEMS,b.item); return `<div class="row-item"><div class="ph"><img src="${i.img}" alt=""></div><div><b>${i.title}</b><span>${b.when}${b.note?' · '+b.note:''}</span></div><div class="r"><span class="pill ${b.status==='Done'?'pill-soft':b.status==='On my way'?'pill-coral':'pill-ok'}">${b.status}</span><span>${b.price?gbp2(b.price):'Plan'}${b.paid?' · paid':''}</span></div></div>`; };
  return `${nav('myjobs')}<section class="section tight" style="padding-top:34px"><div class="wrap"><div class="acct"><div><div class="who"><img src="${PEOPLE.me.img}" alt=""><b>${PEOPLE.me.n}</b><span>${PEOPLE.me.addr}</span><br><span class="pill pill-gold">${ico('award',11)} Over-65 rate</span></div><div class="menu">${[['jobs','calendar','My jobs'],['plan','refresh','Care plan'],['invoices','receipt','Invoices'],['details','user','My details']].map(([k,i,l])=>`<button class="${t===k?'on':''}" data-act="acct" data-t="${k}">${ico(i,16)} ${l}</button>`).join('')}</div></div>
    <div>${t==='jobs'?`${next?`<div class="card"><div class="hd"><h3>Next up · ${it.title}</h3><span class="grow"></span><span class="pill pill-ok">${next.when}</span></div><div class="bd"><div class="grid g2"><div><div class="track">${[['Booked','Confirmed by text',true],['Reminder','The evening before',next.status!=='Confirmed'],['On my way','Text with live ETA',next.status==='On my way'||next.status==='Done'],['Done','Photos and invoice by email',next.status==='Done']].map(([b,s,d],i)=>`<div class="s ${d?'done':''} ${!d&&i===1?'now':''}"><b>${b}</b><span>${s}</span></div>`).join('')}</div></div><div><div class="van"><div class="n">${ico('navigation',20)}</div><div><b>Jamie will text when he sets off</b><span>Usually 20 minutes before. You can reply to the text.</span></div></div><div class="mt" style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Reschedule: pick a new slot">${ico('calendar',13)} Reschedule</button><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Message sent to Jamie">${ico('message',13)} Message Jamie</button><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Add to calendar">${ico('plus',13)} Calendar</button></div></div></div></div></div>`:''}<div class="card mt"><div class="hd"><h3>All jobs</h3><span class="grow"></span><a class="btn btn-sm btn-primary" data-act="go" data-to="book">Book another</a></div><div class="bd" style="padding-top:6px">${mine.map(row).join('')}${[byId(S.bookings,'RB-1174')].map(b=>({...b,who:'me'})).map(row).join('')}</div></div>`:
      t==='plan'?`<div class="card pad"><div style="display:flex;gap:16px;align-items:center"><div style="color:var(--gold)">${ico('refresh',32)}</div><div><b style="font-size:1.05rem">Garden care plan · fortnightly lawn</b><div class="muted" style="font-size:.82rem;margin-top:3px">£76 / month · over-65 rate · next visit Thu 18 Sep 10:30 · renews 1 Oct</div></div><span class="grow"></span><button class="btn btn-ghost" data-act="soon" data-msg="Plan paused until you say">Pause</button><button class="btn btn-ghost" data-act="soon">Change day</button></div><div class="divider"></div><div class="grid g3"><div class="stat"><div class="k">Visits this year</div><div class="v">17</div></div><div class="stat"><div class="k">Included extras used</div><div class="v">2/4</div><div class="d sea">hedges ×1, leaves ×1</div></div><div class="stat"><div class="k">Saved vs one-off</div><div class="v">£94</div></div></div></div>`:
      t==='invoices'?`<div class="card"><div class="hd"><h3>Invoices</h3></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Invoice</th><th>Job</th><th>Date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${[['RH-2031','Lawn mowing · care plan','4 Sep','£76.00','Paid · direct debit'],['RH-2018','Hedge trimming','19 Aug','£51.00','Paid · card'],['RH-1994','Grab rails × 2','2 Jul','£110.50','Paid · cash']].map(([id,j,d,a,s])=>`<tr><td><b>${id}</b></td><td>${j}</td><td>${d}</td><td class="num">${a}</td><td><span class="pill pill-ok">${s}</span></td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="PDF downloaded">${ico('download',13)} PDF</button></div></td></tr>`).join('')}</tbody></table></div></div>`:
      `<div class="card pad"><div class="form" style="display:grid;grid-template-columns:1fr 1fr;gap:14px"><div class="field"><label>Name</label><input class="input" value="${PEOPLE.me.n}"></div><div class="field"><label>Mobile</label><input class="input" value="07700 900 321"></div><div class="field" style="grid-column:1/-1"><label>Address</label><input class="input" value="${PEOPLE.me.addr}"></div><div class="field"><label>Access notes</label><input class="input" value="Side gate unlocked · key safe 4471"></div><div class="field"><label>Over-65 rate</label><select class="select"><option>Yes</option><option>No</option></select></div></div><button class="btn btn-primary mt2" data-act="soon" data-msg="Saved">Save</button></div>`}</div></div></div></section>${footer()}`; };

SCREENS.reviews=()=>`${nav('reviews')}<section class="pagehero" style="min-height:320px"><img class="bg" src="${P('hedge1')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">Reviews &amp; areas</span><h1>4.9 from <em>212 reviews</em></h1><p>Pulled from Google and from the review request every customer gets after a job.</p></div></div></section>
  <section class="section"><div class="wrap"><div class="grid g2">${[...REVIEWS,{who:'nadia',stars:5,txt:'Gutters cleared, photos of the before and after sent to me the same day. Booked the next one for spring already.'},{who:'steve',stars:4,txt:'Pressure washed the patio, looks new. Only four stars because he was 15 minutes late, but he texted to say so.'}].map(r=>`<div class="review">${stars(r.stars)}<p>${r.txt}</p><div class="who"><img src="${person(r.who).img}" alt=""><div><b>${person(r.who).n}</b><span>${person(r.who).role.split(' · ')[1]}</span></div></div></div>`).join('')}</div></div></section>
  <section class="section sunk"><div class="wrap"><div class="sec-head"><span class="kicker">Where we work</span><h2>Purbeck, Poole <em>and around</em></h2><p>Based in Swanage. Anywhere in these areas is normal price. A little further and we add a small travel charge, shown before you book.</p></div><div class="areas">${AREAS.map(a=>`<span>${ico('map-pin',13)} ${a}</span>`).join('')}</div></div></section>${footer()}`;

SCREENS.about=()=>`${nav('about')}<section class="pagehero" style="min-height:360px"><img class="bg" src="${P('hs3')}" alt=""><div class="scrim"></div><div class="in"><div class="wrap"><span class="kicker light">About</span><h1>One van, one Jamie, <em>no call centre</em></h1><p>Royal Home &amp; Garden is Jamie Doxey. Ex-Royal Marines, fourteen years in trees and gardens, and the person who answers the phone, turns up and does the job.</p></div></div></section>
  <section class="section"><div class="wrap"><div class="split"><div class="ph"><img src="${PEOPLE.jamie.img}" alt=""><div class="float">${ico('shield-check',26)}<div><b>Jamie Doxey</b><span>Fully insured · DBS checked · Royal Marines 2005–2016</span></div></div></div><div><span class="kicker">The promise</span><h2>Turn up, do it properly, <em>charge what we said</em></h2><p>Fixed prices on the website are the prices. If a job turns out bigger, Jamie tells you before he starts, not after. Over-65s get 15% off everything because that is who taught him to work.</p><ul class="tick-list"><li>${ico('check-circle',18)}<span><b>Text when on the way.</b> With a live ETA.</span></li><li>${ico('check-circle',18)}<span><b>Photos when done.</b> So you can see the job if you were out.</span></li><li>${ico('check-circle',18)}<span><b>Big trees go to Militree.</b> Same Jamie, different kit.</span></li></ul></div></div></div></section>${footer()}`;
