/* OPERATION POSEIDON · admin console (Jamie's side) */
const ADMIN={after:{}};
const ANAV=[
  ['Today',[['overview','layout','Overview'],['bookings','calendar','Bookings & calendar','bk'],['applications','heart','Free place applications','ap'],['sessions','clock','Sessions']]],
  ['Platform',[['courses','play','Courses & content'],['community','messages','Community',3],['members','users','Members']]],
  ['Shop & money',[['orders','bag','Orders','or'],['products','box','Products & stock'],['money','pound','Funding & payouts']]],
  ['Setup',[['settings','cog','Settings']]],
];
const pips=()=>({bk:S.bookingsAdmin.filter(b=>b.new).length,ap:S.apps.filter(a=>a.status==='new').length,or:S.orders.filter(o=>o.new).length});
const stPill=s=>({Confirmed:'pill-ok','Deposit paid':'pill-warn','Under review':'pill-warn',Waitlisted:'pill-coral','To dispatch':'pill-warn',Dispatched:'pill-sea',Complete:'pill-ok',Active:'pill-ok','Past due':'pill-bad',new:'pill-coral',approved:'pill-ok',declined:'pill-soft'}[s]||'pill-soft');
const who=k=>PEOPLE[k];

ADMIN.shell=()=>{
  const pp=pips(); const page=S.adminPage; const titles={overview:['Good morning, Jamie','Tuesday 15 September · Kimmeridge 15°C · high tide 06:52'],bookings:['Bookings & calendar','Every retreat, session and place in one view'],applications:['Free place applications','You read these. Nobody else.'],sessions:['Sessions','Dips, lessons, kayak, climbing and try-dives'],courses:['Courses & content','Upload, order and set free or members-only'],community:['Community','Boards, reports and the people posting'],members:['Members','Crew memberships and free accounts'],orders:['Shop orders','Pack, dispatch, done'],products:['Products & stock','Merch, equipment and bundles'],money:['Funding & payouts','Where the money comes from and where it goes'],settings:['Settings','Brand, payments, emails and the team']};
  return `<div class="shell"><aside class="side"><div class="brand"><img src="${LOGO}" alt=""><div><div class="wm">Operation Poseidon</div><div class="sub">Admin console</div></div></div>
    ${ANAV.map(([g,items])=>`<div class="navlabel">${g}</div>${items.map(([k,i,l,p])=>`<button class="nav ${page===k?'on':''}" data-act="adm-page" data-p="${k}">${ico(i,17)} ${l}${p?(typeof p==='number'?`<span class="pipn">${p}</span>`:pp[p]?`<span class="pipn">${pp[p]}</span>`:''):''}</button>`).join('')}`).join('')}
    <div class="foot"><div class="me"><img src="${PEOPLE.jamie.img}" alt=""><div><div class="n">Jamie Doxey</div><div class="s">Founder · owner</div></div></div><button class="nav" style="margin-top:8px" data-act="go" data-to="home">${ico('external',16)} View public site</button></div></aside>
    <main class="main"><div class="topbar"><div><h1>${titles[page][0]}</h1><div class="sub">${titles[page][1]}</div></div><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Notifications: 2 new bookings, 2 applications, 2 orders">${ico('bell',15)} Notifications</button><button class="btn btn-sm btn-primary" data-act="adm-page" data-p="bookings">${ico('plus',14)} New date</button></div>
    <div class="content">${(ADMIN.pages[page]||ADMIN.pages.overview)()}</div></main></div>`;
};

ADMIN.pages={};
/* ---------- overview ---------- */
ADMIN.pages.overview=()=>{
  const pp=pips(); const r=RETREATS[0]; const weeks=[3,5,4,7,6,9,8,11];
  return `<div class="masthead"><img class="bg" src="${P('surf4')}" alt=""><div class="sc"></div><div class="in"><div><span class="kicker light">Next retreat · ${r.dates}</span><h2>${r.title.split('·')[0]}<em>${r.cap-r.booked} places left</em></h2><p>${r.booked} booked · ${r.free} free places · ${S.apps.filter(a=>a.retreat===r.id&&a.status==='new').length} applications waiting for you.</p></div><span class="grow"></span><div class="spark"><div class="sp"><div class="k">This month</div><div class="v">£3,410</div><div class="d">bookings + shop + members</div></div><div class="sp"><div class="k">Free places funded</div><div class="v">86</div><div class="d">+4 this month</div></div><div class="sp"><div class="k">Crew members</div><div class="v">${MEMBERS.filter(m=>m.plan!=='Free').length+(S.member?1:0)}</div><div class="d">£${(MEMBERS.filter(m=>m.plan!=='Free').length+(S.member?1:0))*9}/mo recurring</div></div></div></div></div>
  <div class="grid g4"><div class="stat"><div class="k">New bookings</div><div class="v">${pp.bk}</div><div class="d up">${ico('trending-up',12)} 2 today</div></div><div class="stat"><div class="k">Applications to read</div><div class="v">${pp.ap}</div><div class="d coral">${ico('heart',12)} reply within 2 days</div></div><div class="stat"><div class="k">Orders to dispatch</div><div class="v">${pp.or}</div><div class="d sea">${ico('truck',12)} pack tonight</div></div><div class="stat"><div class="k">Course completions</div><div class="v">38</div><div class="d up">${ico('play',12)} this week</div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Bookings per week</h3><span class="grow"></span><span class="pill pill-soft">Last 8 weeks</span></div><div class="bd"><div class="mini">${weeks.map((w,i)=>`<span class="${i===7?'hi':''}" style="height:${Math.round(w/11*80)}px"></span>`).join('')}</div><div class="minilab">${['W28','W29','W30','W31','W32','W33','W34','W35'].map(x=>`<span>${x}</span>`).join('')}</div></div></div>
    <div class="card"><div class="hd"><h3>Where September’s money came from</h3></div><div class="bd"><div class="barrow">${[['Retreat bookings',1840,'#0E6B7C'],['Shop orders',742,'#E2643C'],['Crew memberships',558,'#0A2740'],['Sponsored places',245,'#1E7F5C'],['Sessions',225,'#5FBCCB']].map(([n,v,c])=>`<div class="b"><span class="nm">${n}</span><span class="tr"><i style="width:${v/1840*100}%;background:${c}"></i></span><span class="vv">${gbp(v)}</span></div>`).join('')}</div></div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Latest bookings</h3><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="adm-page" data-p="bookings">All</button></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Who</th><th>Retreat</th><th>Type</th><th>Status</th></tr></thead><tbody>${S.bookingsAdmin.slice(0,5).map(b=>`<tr data-act="booking-open" data-id="${b.id}" style="cursor:pointer"><td><div class="thumbcell"><img src="${who(b.who).img}" alt=""><div><b>${who(b.who).n}</b><div class="s">${b.when}</div></div></div></td><td>${byId(RETREATS,b.retreat).title.split('·')[0]}</td><td>${b.type}</td><td><span class="pill ${stPill(b.status)}">${b.status}</span></td></tr>`).join('')}</tbody></table></div></div>
    <div class="card"><div class="hd"><h3>Applications waiting</h3><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="adm-page" data-p="applications">Read all</button></div><div class="bd">${S.apps.filter(a=>a.status==='new').slice(0,2).map(a=>`<div class="row-item"><img src="${who(a.who).img}" style="width:44px;height:44px;border-radius:50%;object-fit:cover" alt=""><div><b>${who(a.who).n}</b><span>${byId(RETREATS,a.retreat).title.split('·')[0]} · ${a.ref}</span></div><div class="r"><button class="btn btn-sm btn-primary" data-act="app-open" data-id="${a.id}">Read</button></div></div>`).join('')||'<div class="empty" style="padding:20px">All read. Nice.</div>'}</div></div></div>`;
};
/* ---------- bookings + calendar ---------- */
ADMIN.pages.bookings=()=>{
  const days=[];for(let i=0;i<35;i++){const d=i-3; days.push(d<1||d>31?null:d);} // Oct 2026 starts Thu
  const ev={3:['Autumn Reset · 9/12','navy'],4:['Autumn Reset day 2','navy'],8:['Live: Ask Jamie','gold'],10:['Dawn dip','coral'],17:['Dawn dip','coral'],19:['Veterans’ week','sea'],20:['Veterans’ week','sea'],21:['Veterans’ week','sea'],22:['Veterans’ week','sea'],23:['Veterans’ week','sea'],24:['Surf lesson · 4','coral'],31:['Dawn dip','coral']};
  return `<div class="grid g4"><div class="stat"><div class="k">Confirmed · Oct</div><div class="v">${S.bookingsAdmin.filter(b=>b.status==='Confirmed').length+13}</div><div class="d sea">${ico('calendar',12)} 2 retreats, 6 sessions</div></div><div class="stat"><div class="k">Deposits outstanding</div><div class="v">£370</div><div class="d coral">${ico('clock',12)} 2 balances due 19 Sep</div></div><div class="stat"><div class="k">Free places · Oct</div><div class="v">12</div><div class="d up">${ico('heart',12)} 8 veterans, 4 Autumn Reset</div></div><div class="stat"><div class="k">Waitlist</div><div class="v">6</div><div class="d sea">${ico('users',12)} Veterans’ week</div></div></div>
  <div class="card mt"><div class="hd"><h3>October 2026</h3><span class="grow"></span><div class="chips"><button class="chip on">Month</button><button class="chip" data-act="soon">Week</button><button class="chip" data-act="soon">List</button></div><button class="btn btn-sm btn-primary" data-act="soon" data-msg="New retreat date form opens">${ico('plus',13)} Add date</button></div><div class="bd"><div class="cal">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="dh">${d}</div>`).join('')}${days.map(d=>d?`<div class="d ${d===3?'today':''}">${d}${ev[d]?`<span class="ev ${ev[d][1]}">${ev[d][0]}</span>`:''}</div>`:'<div class="d off"></div>').join('')}</div></div></div>
  <div class="card mt"><div class="hd"><h3>All bookings</h3><span class="grow"></span><div class="chips"><button class="chip on">All</button><button class="chip" data-act="soon">Paid</button><button class="chip" data-act="soon">Deposits</button><button class="chip" data-act="soon">Funded</button><button class="chip" data-act="soon">Waitlist</button></div><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="CSV exported">${ico('download',13)} Export</button></div>
    <div class="tblwrap"><table class="tbl"><thead><tr><th>Ref</th><th>Who</th><th>Retreat</th><th>Type</th><th>Paid</th><th>Status</th><th>When</th><th></th></tr></thead><tbody>${S.bookingsAdmin.map(b=>`<tr><td><b>${b.id}</b>${b.new?' <span class="pill pill-coral">New</span>':''}</td><td><div class="thumbcell"><img src="${who(b.who).img}" alt=""><div><b>${who(b.who).n}</b></div></div></td><td>${byId(RETREATS,b.retreat).title}</td><td>${b.type}</td><td class="num">${b.paid?gbp(b.paid):'—'}</td><td><span class="pill ${stPill(b.status)}">${b.status}</span></td><td>${b.when}</td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="booking-open" data-id="${b.id}">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="card mt"><div class="hd"><h3>Retreat capacity</h3></div><div class="bd"><div class="barrow">${RETREATS.map(r=>`<div class="b"><span class="nm">${r.title}</span><span class="tr"><i style="width:${r.booked/r.cap*100}%" class="${r.booked>=r.cap?'coral':''}"></i></span><span class="vv">${r.booked}/${r.cap}</span></div>`).join('')}</div></div></div>`;
};
/* ---------- applications ---------- */
ADMIN.pages.applications=()=>{
  const card=a=>`<div class="appcard"><div class="who"><img src="${who(a.who).img}" alt=""><div><b>${who(a.who).n}</b><span>${byId(RETREATS,a.retreat).title} · ${a.when}</span></div><span class="pill ${stPill(a.status)}">${a.status==='new'?'To read':a.status==='approved'?'Approved':'Not this time'}</span></div><blockquote>${a.txt}</blockquote><div class="facts"><span>${ico('user-check',13)} ${a.ref}</span><span>${ico('wave',13)} ${a.swim}</span><span>${ico('activity',13)} ${a.medical}</span></div>${a.note?`<div class="facts" style="color:var(--sea)"><span>${ico('info',13)} ${a.note}</span></div>`:''}<div class="acts">${a.status==='new'?`<button class="btn btn-sm btn-sea" data-act="app-approve" data-id="${a.id}">${ico('check',13)} Approve free place</button><button class="btn btn-sm btn-ghost" data-act="app-decline" data-id="${a.id}">Not this time</button><button class="btn btn-sm btn-ghost" data-act="app-open" data-id="${a.id}">${ico('message',13)} Message</button>`:`<button class="btn btn-sm btn-ghost" data-act="app-open" data-id="${a.id}">Open</button>`}</div></div>`;
  const news=S.apps.filter(a=>a.status==='new'), rest=S.apps.filter(a=>a.status!=='new');
  return `<div class="grid g4"><div class="stat"><div class="k">To read</div><div class="v">${news.length}</div><div class="d coral">${ico('clock',12)} oldest: yesterday</div></div><div class="stat"><div class="k">Approved this year</div><div class="v">61</div><div class="d up">${ico('heart',12)} 71% of applications</div></div><div class="stat"><div class="k">Free places open</div><div class="v">${RETREATS.reduce((a,r)=>a+r.free,0)}</div><div class="d sea">${ico('calendar',12)} next 4 dates</div></div><div class="stat"><div class="k">Referral partners</div><div class="v">6</div><div class="d sea">${ico('users',12)} Dorset Mind, Op Courage, 4 units</div></div></div>
  <div class="pagehead mt2"><div><h2>Waiting for you</h2><p>Approve and the place is confirmed like a paid one. Decline sends a kind reply with the next date. Nothing here is visible to anyone else.</p></div></div><div class="app">${news.map(card).join('')||'<div class="card"><div class="empty">All read.</div></div>'}</div>
  <div class="pagehead mt3"><div><h2>Decided</h2></div></div><div class="app">${rest.map(card).join('')}</div>`;
};
/* ---------- sessions ---------- */
ADMIN.pages.sessions=()=>`<div class="card"><div class="hd"><h3>Upcoming sessions</h3><span class="grow"></span><button class="btn btn-sm btn-primary" data-act="soon" data-msg="New session form opens">${ico('plus',13)} Add session</button></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Session</th><th>When</th><th>Where</th><th>Lead</th><th>Price</th><th>Booked</th><th>Public</th><th></th></tr></thead><tbody>${SESSIONS.map(s=>`<tr><td><div class="thumbcell"><img class="sq" src="${s.img}" alt=""><div><b>${s.title}</b></div></div></td><td>${s.when}</td><td>${s.loc}</td><td>${who(s.lead).n}</td><td class="num">${s.price?gbp(s.price):'Free'}</td><td class="num">${8-s.spots}/8</td><td><span class="tog on" data-act="toggle"></span></td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Attendee list opens">Attendees</button><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Session templates</h3></div><div class="bd">${['Dawn Dip · free · 8 spots · 45 min','Beginner surf lesson · £35 · 6 spots · 2 h','Sea kayak · £40 · 6 spots · 3 h','Intro to climbing · £40 · 6 spots · 3 h','Try dive · £30 · 4 spots · 1.5 h'].map(t=>`<div class="row-item"><div style="color:var(--sea)">${ico('clock',18)}</div><div><b>${t.split(' · ')[0]}</b><span>${t.split(' · ').slice(1).join(' · ')}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Date picker opens">Schedule</button></div></div>`).join('')}</div></div><div class="card"><div class="hd"><h3>Reminders</h3></div><div class="bd">${[['24 h before','Email + WhatsApp with tide, kit and meeting point',true],['2 h before','WhatsApp: “still on, sea 15°C, see you at 7”',true],['After','Thanks, photo link, log your dip prompt',true],['No-show','Gentle nudge and rebook link',false]].map(([t,s,on])=>`<div class="row-item"><div><b>${t}</b><span>${s}</span></div><div class="r"><span class="tog ${on?'on':''}" data-act="toggle"></span></div></div>`).join('')}</div></div></div>`;
/* ---------- courses ---------- */
ADMIN.pages.courses=()=>`<div class="grid g4"><div class="stat"><div class="k">Courses</div><div class="v">${COURSES.length}</div><div class="d sea">${COURSES.filter(c=>c.tier==='free').length} free · ${COURSES.filter(c=>c.tier==='member').length} members</div></div><div class="stat"><div class="k">Lessons watched · 30d</div><div class="v">1,204</div><div class="d up">${ico('trending-up',12)} +18%</div></div><div class="stat"><div class="k">Completions</div><div class="v">38</div><div class="d up">${ico('award',12)} this week</div></div><div class="stat"><div class="k">Most watched</div><div class="v" style="font-size:1.1rem">Cold Water Shock</div><div class="d sea">${ico('play',12)} 412 plays</div></div></div>
  <div class="card mt"><div class="hd"><h3>Library</h3><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Drag to reorder">${ico('list',13)} Reorder</button><button class="btn btn-sm btn-primary" data-act="soon" data-msg="Upload: drop a video or record straight from your phone">${ico('upload',13)} Upload lesson</button></div>
    <div class="tblwrap"><table class="tbl"><thead><tr><th>Course</th><th>Category</th><th>Lessons</th><th>Plays · 30d</th><th>Completion</th><th>Access</th><th></th></tr></thead><tbody>${COURSES.map((c,i)=>`<tr><td><div class="thumbcell"><img class="sq" src="${c.img}" alt=""><div><b>${c.title}</b><div class="s">${who(c.lead).n} · ${c.dur}</div></div></div></td><td>${c.cat}</td><td class="num">${c.lessons}</td><td class="num">${[412,388,201,176,240,98,64,71,55,120][i]}</td><td><div class="prog" style="width:90px"><i style="width:${[92,81,64,70,44,38,52,41,36,61][i]}%"></i></div></td><td><button class="pill ${c.tier==='free'?'pill-free':'pill-navy'}" data-act="tier-toggle" data-id="${c.id}" title="Click to switch">${ico(c.tier==='free'?'unlock':'lock',10)} ${c.tier==='free'?'Free':'Members'}</button></td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="go" data-to="course" data-id="${c.id}">Preview</button><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Live sessions</h3></div><div class="bd">${[['08','Oct','Ask Jamie anything · October','19:30 · Zoom · members · 41 registered'],['05','Nov','Winter water: staying safe','19:30 · open to all · 12 registered']].map(([d,m,t,s])=>`<div class="event-row"><div class="d"><b>${d}</b><span>${m}</span></div><div class="t"><b>${t}</b><span>${s}</span></div><span class="grow"></span><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Zoom link copied">Link</button></div>`).join('')}<button class="btn btn-sm btn-primary mt" data-act="soon" data-msg="Schedule a live session">${ico('video',13)} Schedule live</button></div></div><div class="card"><div class="hd"><h3>Drip &amp; unlock rules</h3></div><div class="bd">${[['Booking unlocks “Preparing for your retreat”','On',true],['Cold Water Shock required before winter dip bookings','On',true],['Members get new lessons 7 days early','On',true],['Free accounts see first lesson of member courses','Off',false]].map(([t,s,on])=>`<div class="row-item"><div><b>${t}</b></div><div class="r"><span class="tog ${on?'on':''}" data-act="toggle"></span></div></div>`).join('')}</div></div></div>`;
/* ---------- community ---------- */
ADMIN.pages.community=()=>`<div class="grid g4"><div class="stat"><div class="k">Posts · 7d</div><div class="v">64</div><div class="d up">${ico('trending-up',12)} +22%</div></div><div class="stat"><div class="k">Active members · 7d</div><div class="v">214</div><div class="d sea">${ico('users',12)} of 380</div></div><div class="stat"><div class="k">Reports to review</div><div class="v">3</div><div class="d coral">${ico('alert',12)} none urgent</div></div><div class="stat"><div class="k">Dips logged · month</div><div class="v">1,312</div><div class="d up">${ico('sunrise',12)} record</div></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Reported / flagged</h3></div><div class="bd">${[['sophie','Flagged own post for deletion','“Posted in the wrong board, sorry”','Move to Ask the crew'],['josh','Keyword flag: medication','Wellbeing tips reply mentions dosage','Review'],['ellie','Photo without consent?','Dip of the Day photo includes a bystander','Blur & approve']].map(([w,t,s,a])=>`<div class="row-item"><img src="${who(w).img}" style="width:40px;height:40px;border-radius:50%;object-fit:cover" alt=""><div><b>${t}</b><span>${who(w).n} · ${s}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="${a} · done">${a}</button></div></div>`).join('')}</div></div>
    <div class="card"><div class="hd"><h3>Boards</h3><span class="grow"></span><button class="btn btn-sm btn-primary" data-act="soon" data-msg="New board form opens">${ico('plus',13)} New board</button></div><div class="bd">${BOARDS.slice(1).map(([n,i,c])=>`<div class="row-item"><div style="color:var(--sea)">${ico(i,18)}</div><div><b>${n}</b><span>${c} posts · ${n==='Announcements'?'Jamie only':n.includes('cohort')?'Private · retreat attendees':'Members can post'}</span></div><div class="r"><span class="tog on" data-act="toggle"></span></div></div>`).join('')}</div></div></div>
  <div class="card mt"><div class="hd"><h3>Safeguarding keywords</h3><span class="s">Posts containing these are held for you before going live. Members are shown a support message with Samaritans and Op Courage numbers.</span></div><div class="bd"><div class="chips">${['suicide','self harm','overdose','medication','can’t go on','crisis'].map(k=>`<span class="chip">${k} ${ico('x',12)}</span>`).join('')}<button class="chip" data-act="soon">${ico('plus',12)} Add</button></div></div></div>`;
/* ---------- members ---------- */
ADMIN.pages.members=()=>{
  const rows=[...MEMBERS.map(m=>({...m,who:m.who})),];
  if(S.member) rows[0]={who:'me',plan:S.plan,since:'Today',status:'Active',ltv:S.plan.includes('Annual')?79:9}; else rows[0]={who:'me',plan:'Free',since:'Mar 2026',status:'Active',ltv:0};
  const crew=rows.filter(r=>r.plan!=='Free').length;
  return `<div class="grid g4"><div class="stat"><div class="k">Crew members</div><div class="v">${crew+143}</div><div class="d up">${ico('trending-up',12)} +11 this month</div></div><div class="stat"><div class="k">Monthly recurring</div><div class="v">£${(crew+143)*9-120}</div><div class="d sea">${ico('refresh',12)} incl. annual spread</div></div><div class="stat"><div class="k">Free accounts</div><div class="v">231</div><div class="d sea">${ico('users',12)} 38% convert in 60d</div></div><div class="stat"><div class="k">Places funded by members</div><div class="v">${Math.floor((crew+143)/12)}</div><div class="d coral">${ico('heart',12)} 12 members = 1 place</div></div></div>
  <div class="card mt"><div class="hd"><h3>People</h3><span class="grow"></span><div class="toolbar" style="margin:0"><div class="search">${ico('search',15)}<input placeholder="Search name or email"></div></div><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Email composer opens for 152 crew members">${ico('mail',13)} Email crew</button></div>
    <div class="tblwrap"><table class="tbl"><thead><tr><th>Member</th><th>Plan</th><th>Since</th><th>Status</th><th>Bookings</th><th>Dips</th><th>Lifetime</th><th></th></tr></thead><tbody>${rows.map((m,i)=>`<tr><td><div class="thumbcell"><img src="${who(m.who).img}" alt=""><div><b>${who(m.who).n}</b><div class="s">${who(m.who).role}</div></div></div></td><td>${m.plan}</td><td>${m.since}</td><td><span class="pill ${stPill(m.status)}">${m.status}</span></td><td class="num">${[2,3,1,2,4,1,0][i]}</td><td class="num">${[17,41,6,22,58,3,1][i]}</td><td class="num">${gbp(m.ltv+[245,290,0,305,374,0,38][i])}</td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Member profile opens">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>`;
};
/* ---------- orders ---------- */
ADMIN.pages.orders=()=>`<div class="grid g4"><div class="stat"><div class="k">To dispatch</div><div class="v">${S.orders.filter(o=>o.status==='To dispatch').length}</div><div class="d coral">${ico('truck',12)} pack tonight</div></div><div class="stat"><div class="k">Shop revenue · Sep</div><div class="v">£742</div><div class="d up">${ico('trending-up',12)} +31%</div></div><div class="stat"><div class="k">Avg order</div><div class="v">£46</div><div class="d sea">${ico('bag',12)} 1.8 items</div></div><div class="stat"><div class="k">To free places</div><div class="v">£260</div><div class="d up">${ico('heart',12)} 35% of shop</div></div></div>
  <div class="card mt"><div class="hd"><h3>Orders</h3><span class="grow"></span><div class="chips"><button class="chip on">All</button><button class="chip" data-act="soon">To dispatch</button><button class="chip" data-act="soon">Dispatched</button><button class="chip" data-act="soon">Complete</button></div><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Royal Mail labels printed">${ico('printer',13)} Print labels</button></div>
    <div class="tblwrap"><table class="tbl"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Placed</th><th></th></tr></thead><tbody>${S.orders.map(o=>`<tr><td><b>${o.id}</b>${o.new?' <span class="pill pill-coral">New</span>':''}</td><td><div class="thumbcell"><img src="${who(o.who).img}" alt=""><div><b>${who(o.who).n}</b></div></div></td><td>${o.items}</td><td class="num">${gbp2(o.tot)}</td><td><span class="pill ${stPill(o.status)}">${o.status}</span></td><td>${o.when}</td><td><div class="acts">${o.status==='To dispatch'?`<button class="btn btn-sm btn-sea" data-act="order-dispatch" data-id="${o.id}">${ico('truck',13)} Dispatch</button>`:''}<button class="btn btn-sm btn-ghost" data-act="order-open" data-id="${o.id}">Open</button></div></td></tr>`).join('')}</tbody></table></div></div>`;
/* ---------- products ---------- */
ADMIN.pages.products=()=>`<div class="card"><div class="hd"><h3>Products</h3><span class="grow"></span><button class="btn btn-sm btn-primary" data-act="soon" data-msg="New product form opens">${ico('plus',13)} Add product</button></div>
  <div class="tblwrap"><table class="tbl"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Sold · 30d</th><th>Funds</th><th>Live</th><th></th></tr></thead><tbody>${PRODUCTS.map((p,i)=>`<tr><td><div class="thumbcell"><div style="width:40px;height:40px;border-radius:10px;background:var(--sunk);overflow:hidden">${merchSVG(p.type,p.col)}</div><div><b>${p.name}</b></div></div></td><td>${p.cat}</td><td class="num">${gbp(p.price)}${p.was?` <s style="color:var(--ink-3);font-weight:500">${gbp(p.was)}</s>`:''}</td><td><span class="pill ${p.stock<10?'pill-coral':p.stock<20?'pill-warn':'pill-ok'}">${p.stock>500?'Unlimited':p.stock+' left'}</span></td><td class="num">${[14,9,21,33,6,12,4,7,3,5][i]}</td><td style="font-size:.76rem">${p.funds}</td><td><span class="tog on" data-act="toggle"></span></td><td><div class="acts"><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></td></tr>`).join('')}</tbody></table></div></div>
  <div class="grid g2 mt"><div class="card"><div class="hd"><h3>Low stock</h3></div><div class="bd">${PRODUCTS.filter(p=>p.stock<15).map(p=>`<div class="row-item"><div style="width:44px;height:44px;border-radius:10px;background:var(--sunk);overflow:hidden">${merchSVG(p.type,p.col)}</div><div><b>${p.name}</b><span>${p.stock} left · sells ${[2,1][0]}/week</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon" data-msg="Reorder note sent to supplier">Reorder</button></div></div>`).join('')}</div></div><div class="card"><div class="hd"><h3>Fulfilment</h3></div><div class="bd">${[['Ship from','Kimmeridge lock-up · Royal Mail 48'],['Print on demand','Tees & hoodies via Teemill (no stock held)'],['Collect at retreat','Enabled · saves postage, shown at checkout'],['Member discount','10% · applied automatically']].map(([k,v])=>`<div class="row-item"><div><b>${k}</b><span>${v}</span></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></div>`).join('')}</div></div></div>`;
/* ---------- money ---------- */
ADMIN.pages.money=()=>`<div class="masthead" style="min-height:180px"><img class="bg" src="${P('sea5')}" alt=""><div class="sc"></div><div class="in"><div><span class="kicker light">Free places fund</span><h2>£<em>2,840</em> in the pot</h2><p>Enough for 11 more funded places. Every booking, order and membership tops it up automatically.</p></div><span class="grow"></span><div class="spark"><div class="sp"><div class="k">Sep income</div><div class="v">£3,610</div></div><div class="sp"><div class="k">To fund</div><div class="v">£1,190</div><div class="d">33%</div></div><div class="sp"><div class="k">Next payout</div><div class="v">Fri</div><div class="d">£2,140 to bank</div></div></div></div></div>
  <div class="grid g2"><div class="card"><div class="hd"><h3>Income by source · 2026</h3></div><div class="bd"><div class="barrow">${[['Retreat bookings',14200],['Crew memberships',5120],['Shop',4120],['Sponsored places',2450],['Sessions',1830],['Forestry contribution (Jamie)',9000]].map(([n,v])=>`<div class="b"><span class="nm">${n}</span><span class="tr"><i style="width:${v/14200*100}%" class="${n.includes('Forestry')?'coral':''}"></i></span><span class="vv">${gbp(v)}</span></div>`).join('')}</div></div></div>
    <div class="card"><div class="hd"><h3>Payouts</h3><span class="grow"></span><span class="pill pill-ok">Stripe connected</span></div><div class="tblwrap"><table class="tbl"><thead><tr><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>${[['Fri 18 Sep','£2,140','Scheduled','pill-warn'],['Fri 11 Sep','£1,865','Paid','pill-ok'],['Fri 4 Sep','£2,310','Paid','pill-ok'],['Fri 28 Aug','£1,420','Paid','pill-ok']].map(([d,a,s,c])=>`<tr><td>${d}</td><td class="num">${a}</td><td><span class="pill ${c}">${s}</span></td></tr>`).join('')}</tbody></table></div></div></div>
  <div class="card mt"><div class="hd"><h3>Fund rules</h3><span class="s">How much of each income type goes into the free places pot.</span></div><div class="bd"><div class="grid g4">${[['Retreat bookings','20%'],['Shop orders','35%'],['Memberships','70%'],['Sponsored places','100%']].map(([k,v])=>`<div class="stat"><div class="k">${k}</div><div class="v">${v}</div><div class="d sea"><button data-act="soon" data-msg="Edit rule">Edit</button></div></div>`).join('')}</div></div></div>`;
/* ---------- settings ---------- */
ADMIN.pages.settings=()=>`<div class="grid g2">${[['Brand','Logo, colours, the wave. Public site copy.',['Logo uploaded','Colours: navy, sea, coral','Domain: opposeidon.co.uk']],['Payments','Stripe for cards, Apple Pay and Google Pay. Weekly payouts.',['Stripe: connected','Payouts: Fridays','Deposits: 14 days before']],['Emails & WhatsApp','Confirmations, reminders and the free-place replies.',['Booking confirmation','24 h reminder','Kind decline template']],['Team','Who can see what. Applications are owner-only.',['Jamie · Owner','Hannah · Sessions & community','Kate · Courses']],['Waivers & safety','Digital waiver signed at booking. Medical info kept private.',['Waiver v3 · live','Cold water briefing required','Lifeguard rota']],['Integrations','Instagram feed, tide data, Zoom, Teemill print-on-demand.',['Instagram: @opposeidon','Tides: Kimmeridge','Zoom: linked']]].map(([t,s,items])=>`<div class="card pad"><b style="font-size:1rem">${t}</b><p class="muted" style="font-size:.84rem;margin-top:6px;line-height:1.5">${s}</p><div class="mt">${items.map(i=>`<div class="row-item" style="padding:9px 0"><div style="color:var(--success)">${ico('check-circle',16)}</div><div><b style="font-weight:600">${i}</b></div><div class="r"><button class="btn btn-sm btn-ghost" data-act="soon">Edit</button></div></div>`).join('')}</div></div>`).join('')}</div>`;

/* ---------- drawer ---------- */
ADMIN.drawer=d=>{
  const hd=(t,s)=>`<div class="hd"><div><h3>${t}</h3><div class="muted" style="font-size:.74rem;margin-top:2px">${s}</div></div><span class="grow"></span><button class="btn-icon" data-act="drawer-close">${ico('x',16)}</button></div>`;
  if(d.kind==='app'){ const a=byId(S.apps,d.id); const r=byId(RETREATS,a.retreat); return `${hd('Free place application',a.id.toUpperCase()+' · '+a.when)}<div class="bd"><div class="appcard" style="box-shadow:none"><div class="who"><img src="${who(a.who).img}" alt=""><div><b>${who(a.who).n}</b><span>${a.ref}</span></div><span class="pill ${stPill(a.status)}">${a.status}</span></div><blockquote>${a.txt}</blockquote></div><dl class="kv mt2"><dt>Retreat</dt><dd>${r.title}</dd><dt>Dates</dt><dd>${r.dates}</dd><dt>Free places left</dt><dd>${r.free}</dd><dt>Water confidence</dt><dd>${a.swim}</dd><dt>Medical</dt><dd>${a.medical}</dd><dt>Contact</dt><dd>WhatsApp · email</dd></dl><div class="field mt2"><label>Message ${who(a.who).n.split(' ')[0]}</label><textarea class="textarea" placeholder="Hi ${who(a.who).n.split(' ')[0]}, thanks for writing…"></textarea></div></div><div class="ft">${a.status==='new'?`<button class="btn btn-ghost" data-act="app-decline" data-id="${a.id}">Not this time</button><button class="btn btn-sea" data-act="app-approve" data-id="${a.id}">${ico('check',14)} Approve free place</button>`:`<button class="btn btn-primary" data-act="soon" data-msg="Message sent">${ico('send',14)} Send message</button>`}</div>`; }
  if(d.kind==='booking'){ const b=byId(S.bookingsAdmin,d.id); const r=byId(RETREATS,b.retreat); return `${hd('Booking '+b.id,b.when)}<div class="bd"><div class="row-item" style="border:0"><img src="${who(b.who).img}" style="width:48px;height:48px;border-radius:50%;object-fit:cover" alt=""><div><b>${who(b.who).n}</b><span>${who(b.who).role}</span></div><div class="r"><span class="pill ${stPill(b.status)}">${b.status}</span></div></div><dl class="kv mt"><dt>Retreat</dt><dd>${r.title}</dd><dt>Dates</dt><dd>${r.dates}</dd><dt>Type</dt><dd>${b.type}</dd><dt>Paid</dt><dd>${b.paid?gbp(b.paid):'—'}${b.type==='Deposit'?' · balance '+gbp(r.price-r.deposit)+' due 14 days before':''}</dd><dt>Wetsuit</dt><dd>M · boots UK 9</dd><dt>Medical</dt><dd>None declared</dd><dt>Diet</dt><dd>Vegetarian</dd><dt>Emergency</dt><dd>Sam Whitfield · 07700 900 456</dd><dt>Waiver</dt><dd>Signed at booking</dd><dt>Prep course</dt><dd>2 of 4 lessons watched</dd></dl></div><div class="ft"><button class="btn btn-ghost" data-act="soon" data-msg="Refund / move date options">Move or refund</button><button class="btn btn-primary" data-act="soon" data-msg="WhatsApp opened">${ico('message',14)} Message</button></div>`; }
  if(d.kind==='order'){ const o=byId(S.orders,d.id); return `${hd('Order '+o.id,o.when)}<div class="bd"><div class="row-item" style="border:0"><img src="${who(o.who).img}" style="width:48px;height:48px;border-radius:50%;object-fit:cover" alt=""><div><b>${who(o.who).n}</b><span>14 Harbour Row, Swanage BH19 2AB</span></div><div class="r"><span class="pill ${stPill(o.status)}">${o.status}</span></div></div><dl class="kv mt"><dt>Items</dt><dd>${o.items}</dd><dt>Total</dt><dd>${gbp2(o.tot)}</dd><dt>To fund</dt><dd>${gbp2(o.tot*.35)}</dd><dt>Delivery</dt><dd>Royal Mail 48</dd><dt>Paid</dt><dd>Visa · Stripe</dd></dl></div><div class="ft"><button class="btn btn-ghost" data-act="soon" data-msg="Label printed">${ico('printer',14)} Label</button>${o.status==='To dispatch'?`<button class="btn btn-sea" data-act="order-dispatch" data-id="${o.id}">${ico('truck',14)} Mark dispatched</button>`:''}</div>`; }
  return '';
};
